/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module cut(clk, in, out);
  input clk;
  wire clk;
  input [3:0] in;
  wire [3:0] in;
  output out;
  wire out;
  wire _0_;
  wire _1_;
  \$_NAND_  _2_ (
    .A(in[0]),
    .B(in[1]),
    .Y(_0_)
  );
  \$_NAND_  _3_ (
    .A(in[2]),
    .B(in[3]),
    .Y(_1_)
  );
  \$_NAND_  _4_ (
    .A(_0_),
    .B(_1_),
    .Y(out)
  );
endmodule
