/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

(* hdlname = "controller" *)
(* src = "controller.sv:3.1-149.10" *)
module \$paramod$5a749a99f52c3c2473bfdf42ed69512a64c0e60e\controller (clk, rstn, start_ext, num_detected, start, scan_en, capture_en, done, pass, coverage);
  (* src = "controller.sv:7.24-7.27" *)
  input clk;
  wire clk;
  (* src = "controller.sv:8.24-8.28" *)
  input rstn;
  wire rstn;
  (* src = "controller.sv:11.24-11.33" *)
  input start_ext;
  wire start_ext;
  (* src = "controller.sv:14.24-14.36" *)
  input [3:0] num_detected;
  wire [3:0] num_detected;
  (* src = "controller.sv:17.24-17.29" *)
  output start;
  wire start;
  (* src = "controller.sv:20.24-20.31" *)
  output scan_en;
  wire scan_en;
  (* src = "controller.sv:21.24-21.34" *)
  output capture_en;
  wire capture_en;
  (* src = "controller.sv:24.24-24.28" *)
  output done;
  wire done;
  (* src = "controller.sv:25.24-25.28" *)
  output pass;
  wire pass;
  (* src = "controller.sv:26.24-26.32" *)
  output [6:0] coverage;
  wire [6:0] coverage;
  (* src = "controller.sv:111.5-143.8" *)
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "controller.sv:139.34-139.62" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* force_downto = 32'd1 *)
  (* src = "controller.sv:140.33-140.68|/opt/homebrew/bin/../share/yosys/techmap.v:400.23-400.24" *)
  wire [31:0] _32_;
  (* src = "controller.sv:39.17-39.29" *)
  reg [6:0] coverage_reg;
  (* src = "controller.sv:37.17-37.26" *)
  reg [4:0] cycle_cnt;
  (* src = "controller.sv:38.17-38.25" *)
  reg pass_reg;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  assign _07_ = ~num_detected[3];
  assign _32_[2] = num_detected[2] & num_detected[3];
  assign _08_ = num_detected[2] & ~(num_detected[1]);
  assign _09_ = num_detected[2] ? num_detected[1] : num_detected[3];
  assign _32_[1] = _09_ & ~(_32_[2]);
  assign _10_ = num_detected[3] & _08_;
  assign _11_ = num_detected[0] | num_detected[3];
  assign _12_ = num_detected[1] & ~(num_detected[2]);
  assign _13_ = ~(num_detected[0] & num_detected[3]);
  assign _14_ = ~(_11_ & _12_);
  assign _15_ = ~(_13_ & _14_);
  assign _32_[0] = _08_ ? _07_ : _15_;
  assign _16_ = cycle_cnt[3] & cycle_cnt[2];
  assign _17_ = cycle_cnt[1] & ~(cycle_cnt[0]);
  assign _18_ = _17_ & ~(cycle_cnt[4]);
  assign _19_ = ~(_16_ & _18_);
  assign _20_ = state[2] & _19_;
  assign _21_ = cycle_cnt[0] & cycle_cnt[1];
  assign _22_ = ~(cycle_cnt[2] & _21_);
  assign _23_ = ~(cycle_cnt[3] ^ _22_);
  assign _00_[3] = _20_ & _23_;
  assign _24_ = cycle_cnt[2] ^ _21_;
  assign _00_[2] = _20_ & _24_;
  assign _25_ = cycle_cnt[0] ^ cycle_cnt[1];
  assign _00_[1] = _20_ & _25_;
  assign _00_[0] = _20_ & ~(cycle_cnt[0]);
  assign _01_ = state[0] & ~(start_ext);
  assign _26_ = state[0] | state[3];
  assign _27_ = start_ext & _26_;
  assign _03_ = _20_ | _27_;
  assign _28_ = state[3] & ~(start_ext);
  assign _05_ = state[1] | state[3];
  assign _04_ = state[1] | _28_;
  assign _29_ = ~(state[2] | state[0]);
  assign done = _29_ & ~(state[1]);
  assign _30_ = ~(_16_ & _21_);
  assign _31_ = ~(cycle_cnt[4] ^ _30_);
  assign _00_[4] = state[2] & _31_;
  assign _06_ = _10_ & ~(num_detected[0]);
  assign _02_ = state[2] & ~(_19_);
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) pass_reg <= 1'h0;
    else if (state[1]) pass_reg <= _06_;
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[0] <= 1'h0;
    else if (state[1]) coverage_reg[0] <= _32_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[1] <= 1'h0;
    else if (state[1]) coverage_reg[1] <= _32_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[2] <= 1'h0;
    else if (state[1]) coverage_reg[2] <= _32_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[3] <= 1'h0;
    else if (state[1]) coverage_reg[3] <= num_detected[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[4] <= 1'h0;
    else if (state[1]) coverage_reg[4] <= num_detected[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[5] <= 1'h0;
    else if (state[1]) coverage_reg[5] <= num_detected[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[6] <= 1'h0;
    else if (state[1]) coverage_reg[6] <= num_detected[3];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[0] <= 1'h0;
    else if (!_05_) cycle_cnt[0] <= _00_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[1] <= 1'h0;
    else if (!_05_) cycle_cnt[1] <= _00_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[2] <= 1'h0;
    else if (!_05_) cycle_cnt[2] <= _00_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[3] <= 1'h0;
    else if (!_05_) cycle_cnt[3] <= _00_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[4] <= 1'h0;
    else if (!_05_) cycle_cnt[4] <= _00_[4];
  always @(posedge clk, negedge rstn)
    if (!rstn) state[0] <= 1'h1;
    else state[0] <= _01_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[1] <= 1'h0;
    else state[1] <= _02_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[2] <= 1'h0;
    else state[2] <= _03_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[3] <= 1'h0;
    else state[3] <= _04_;
  assign { _32_[31:8], _32_[6:3] } = { 24'h000000, num_detected };
  assign coverage = coverage_reg;
  assign pass = pass_reg;
  assign capture_en = state[1];
  assign scan_en = done;
  assign start = state[2];
endmodule

(* dynports =  1  *)
(* hdlname = "MISR" *)
(* src = "MISR.sv:1.1-77.10" *)
module \$paramod\MISR\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, smodel, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar, GoodF, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar, Sign_F_at_C
, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Sign_Good);
  (* src = "MISR.sv:4.34-4.37" *)
  input clk;
  wire clk;
  (* src = "MISR.sv:5.34-5.38" *)
  input rstn;
  wire rstn;
  (* src = "MISR.sv:6.34-6.40" *)
  input [3:0] smodel;
  wire [3:0] smodel;
  (* src = "MISR.sv:7.18-7.24" *)
  input F_at_A;
  wire F_at_A;
  (* src = "MISR.sv:7.25-7.34" *)
  input F_at_Abar;
  wire F_at_Abar;
  (* src = "MISR.sv:8.17-8.23" *)
  input F_at_B;
  wire F_at_B;
  (* src = "MISR.sv:8.24-8.33" *)
  input F_at_Bbar;
  wire F_at_Bbar;
  (* src = "MISR.sv:9.17-9.23" *)
  input F_at_C;
  wire F_at_C;
  (* src = "MISR.sv:9.24-9.33" *)
  input F_at_Cbar;
  wire F_at_Cbar;
  (* src = "MISR.sv:10.17-10.23" *)
  input F_at_D;
  wire F_at_D;
  (* src = "MISR.sv:10.24-10.33" *)
  input F_at_Dbar;
  wire F_at_Dbar;
  (* src = "MISR.sv:11.17-11.23" *)
  input F_at_X;
  wire F_at_X;
  (* src = "MISR.sv:11.24-11.33" *)
  input F_at_Xbar;
  wire F_at_Xbar;
  (* src = "MISR.sv:12.17-12.23" *)
  input F_at_Y;
  wire F_at_Y;
  (* src = "MISR.sv:12.24-12.33" *)
  input F_at_Ybar;
  wire F_at_Ybar;
  (* src = "MISR.sv:13.17-13.22" *)
  input GoodF;
  wire GoodF;
  (* src = "MISR.sv:15.34-15.45" *)
  output [3:0] Sign_F_at_A;
  reg [3:0] Sign_F_at_A;
  (* src = "MISR.sv:15.46-15.60" *)
  output [3:0] Sign_F_at_Abar;
  reg [3:0] Sign_F_at_Abar;
  (* src = "MISR.sv:16.17-16.28" *)
  output [3:0] Sign_F_at_B;
  reg [3:0] Sign_F_at_B;
  (* src = "MISR.sv:16.29-16.43" *)
  output [3:0] Sign_F_at_Bbar;
  reg [3:0] Sign_F_at_Bbar;
  (* src = "MISR.sv:17.17-17.28" *)
  output [3:0] Sign_F_at_C;
  reg [3:0] Sign_F_at_C;
  (* src = "MISR.sv:17.29-17.43" *)
  output [3:0] Sign_F_at_Cbar;
  reg [3:0] Sign_F_at_Cbar;
  (* src = "MISR.sv:18.17-18.28" *)
  output [3:0] Sign_F_at_D;
  reg [3:0] Sign_F_at_D;
  (* src = "MISR.sv:18.29-18.43" *)
  output [3:0] Sign_F_at_Dbar;
  reg [3:0] Sign_F_at_Dbar;
  (* src = "MISR.sv:19.17-19.28" *)
  output [3:0] Sign_F_at_X;
  reg [3:0] Sign_F_at_X;
  (* src = "MISR.sv:19.29-19.43" *)
  output [3:0] Sign_F_at_Xbar;
  reg [3:0] Sign_F_at_Xbar;
  (* src = "MISR.sv:20.17-20.28" *)
  output [3:0] Sign_F_at_Y;
  reg [3:0] Sign_F_at_Y;
  (* src = "MISR.sv:20.29-20.43" *)
  output [3:0] Sign_F_at_Ybar;
  reg [3:0] Sign_F_at_Ybar;
  (* src = "MISR.sv:21.17-21.26" *)
  output [3:0] Sign_Good;
  reg [3:0] Sign_Good;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _00_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _01_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _02_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _03_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _04_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _05_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _06_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _07_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _08_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _09_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _10_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _11_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _12_;
  assign _12_[2] = Sign_Good[1] ^ Sign_Good[3];
  assign _12_[0] = Sign_Good[3] ^ GoodF;
  assign _11_[2] = Sign_F_at_Ybar[1] ^ Sign_F_at_Ybar[3];
  assign _11_[0] = Sign_F_at_Ybar[3] ^ F_at_Ybar;
  assign _10_[2] = Sign_F_at_Y[1] ^ Sign_F_at_Y[3];
  assign _10_[0] = Sign_F_at_Y[3] ^ F_at_Y;
  assign _09_[2] = Sign_F_at_Xbar[1] ^ Sign_F_at_Xbar[3];
  assign _09_[0] = Sign_F_at_Xbar[3] ^ F_at_Xbar;
  assign _08_[2] = Sign_F_at_X[1] ^ Sign_F_at_X[3];
  assign _08_[0] = Sign_F_at_X[3] ^ F_at_X;
  assign _07_[2] = Sign_F_at_Dbar[1] ^ Sign_F_at_Dbar[3];
  assign _07_[0] = Sign_F_at_Dbar[3] ^ F_at_Dbar;
  assign _06_[2] = Sign_F_at_D[1] ^ Sign_F_at_D[3];
  assign _06_[0] = Sign_F_at_D[3] ^ F_at_D;
  assign _05_[2] = Sign_F_at_Cbar[1] ^ Sign_F_at_Cbar[3];
  assign _05_[0] = Sign_F_at_Cbar[3] ^ F_at_Cbar;
  assign _04_[2] = Sign_F_at_C[1] ^ Sign_F_at_C[3];
  assign _04_[0] = Sign_F_at_C[3] ^ F_at_C;
  assign _03_[2] = Sign_F_at_Bbar[1] ^ Sign_F_at_Bbar[3];
  assign _03_[0] = Sign_F_at_Bbar[3] ^ F_at_Bbar;
  assign _02_[2] = Sign_F_at_B[1] ^ Sign_F_at_B[3];
  assign _02_[0] = Sign_F_at_B[3] ^ F_at_B;
  assign _01_[2] = Sign_F_at_Abar[1] ^ Sign_F_at_Abar[3];
  assign _01_[0] = Sign_F_at_Abar[3] ^ F_at_Abar;
  assign _00_[2] = Sign_F_at_A[1] ^ Sign_F_at_A[3];
  assign _00_[0] = Sign_F_at_A[3] ^ F_at_A;
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[0] <= 1'h0;
    else Sign_F_at_A[0] <= _00_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[1] <= 1'h0;
    else Sign_F_at_A[1] <= Sign_F_at_A[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[2] <= 1'h0;
    else Sign_F_at_A[2] <= _00_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[3] <= 1'h1;
    else Sign_F_at_A[3] <= Sign_F_at_A[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[0] <= 1'h0;
    else Sign_F_at_Abar[0] <= _01_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[1] <= 1'h0;
    else Sign_F_at_Abar[1] <= Sign_F_at_Abar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[2] <= 1'h0;
    else Sign_F_at_Abar[2] <= _01_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[3] <= 1'h1;
    else Sign_F_at_Abar[3] <= Sign_F_at_Abar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[0] <= 1'h0;
    else Sign_F_at_B[0] <= _02_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[1] <= 1'h0;
    else Sign_F_at_B[1] <= Sign_F_at_B[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[2] <= 1'h0;
    else Sign_F_at_B[2] <= _02_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[3] <= 1'h1;
    else Sign_F_at_B[3] <= Sign_F_at_B[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[0] <= 1'h0;
    else Sign_F_at_Bbar[0] <= _03_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[1] <= 1'h0;
    else Sign_F_at_Bbar[1] <= Sign_F_at_Bbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[2] <= 1'h0;
    else Sign_F_at_Bbar[2] <= _03_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[3] <= 1'h1;
    else Sign_F_at_Bbar[3] <= Sign_F_at_Bbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[0] <= 1'h0;
    else Sign_F_at_C[0] <= _04_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[1] <= 1'h0;
    else Sign_F_at_C[1] <= Sign_F_at_C[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[2] <= 1'h0;
    else Sign_F_at_C[2] <= _04_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[3] <= 1'h1;
    else Sign_F_at_C[3] <= Sign_F_at_C[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[0] <= 1'h0;
    else Sign_F_at_Cbar[0] <= _05_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[1] <= 1'h0;
    else Sign_F_at_Cbar[1] <= Sign_F_at_Cbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[2] <= 1'h0;
    else Sign_F_at_Cbar[2] <= _05_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[3] <= 1'h1;
    else Sign_F_at_Cbar[3] <= Sign_F_at_Cbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[0] <= 1'h0;
    else Sign_F_at_D[0] <= _06_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[1] <= 1'h0;
    else Sign_F_at_D[1] <= Sign_F_at_D[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[2] <= 1'h0;
    else Sign_F_at_D[2] <= _06_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[3] <= 1'h1;
    else Sign_F_at_D[3] <= Sign_F_at_D[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[0] <= 1'h0;
    else Sign_F_at_Dbar[0] <= _07_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[1] <= 1'h0;
    else Sign_F_at_Dbar[1] <= Sign_F_at_Dbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[2] <= 1'h0;
    else Sign_F_at_Dbar[2] <= _07_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[3] <= 1'h1;
    else Sign_F_at_Dbar[3] <= Sign_F_at_Dbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[0] <= 1'h0;
    else Sign_F_at_X[0] <= _08_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[1] <= 1'h0;
    else Sign_F_at_X[1] <= Sign_F_at_X[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[2] <= 1'h0;
    else Sign_F_at_X[2] <= _08_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[3] <= 1'h1;
    else Sign_F_at_X[3] <= Sign_F_at_X[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[0] <= 1'h0;
    else Sign_F_at_Xbar[0] <= _09_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[1] <= 1'h0;
    else Sign_F_at_Xbar[1] <= Sign_F_at_Xbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[2] <= 1'h0;
    else Sign_F_at_Xbar[2] <= _09_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[3] <= 1'h1;
    else Sign_F_at_Xbar[3] <= Sign_F_at_Xbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[0] <= 1'h0;
    else Sign_F_at_Y[0] <= _10_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[1] <= 1'h0;
    else Sign_F_at_Y[1] <= Sign_F_at_Y[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[2] <= 1'h0;
    else Sign_F_at_Y[2] <= _10_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[3] <= 1'h1;
    else Sign_F_at_Y[3] <= Sign_F_at_Y[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[0] <= 1'h0;
    else Sign_F_at_Ybar[0] <= _11_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[1] <= 1'h0;
    else Sign_F_at_Ybar[1] <= Sign_F_at_Ybar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[2] <= 1'h0;
    else Sign_F_at_Ybar[2] <= _11_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[3] <= 1'h1;
    else Sign_F_at_Ybar[3] <= Sign_F_at_Ybar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[0] <= 1'h0;
    else Sign_Good[0] <= _12_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[1] <= 1'h0;
    else Sign_Good[1] <= Sign_Good[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[2] <= 1'h0;
    else Sign_Good[2] <= _12_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[3] <= 1'h1;
    else Sign_Good[3] <= Sign_Good[2];
  assign { _12_[3], _12_[1] } = { Sign_Good[2], Sign_Good[0] };
  assign { _11_[3], _11_[1] } = { Sign_F_at_Ybar[2], Sign_F_at_Ybar[0] };
  assign { _10_[3], _10_[1] } = { Sign_F_at_Y[2], Sign_F_at_Y[0] };
  assign { _09_[3], _09_[1] } = { Sign_F_at_Xbar[2], Sign_F_at_Xbar[0] };
  assign { _08_[3], _08_[1] } = { Sign_F_at_X[2], Sign_F_at_X[0] };
  assign { _07_[3], _07_[1] } = { Sign_F_at_Dbar[2], Sign_F_at_Dbar[0] };
  assign { _06_[3], _06_[1] } = { Sign_F_at_D[2], Sign_F_at_D[0] };
  assign { _05_[3], _05_[1] } = { Sign_F_at_Cbar[2], Sign_F_at_Cbar[0] };
  assign { _04_[3], _04_[1] } = { Sign_F_at_C[2], Sign_F_at_C[0] };
  assign { _03_[3], _03_[1] } = { Sign_F_at_Bbar[2], Sign_F_at_Bbar[0] };
  assign { _02_[3], _02_[1] } = { Sign_F_at_B[2], Sign_F_at_B[0] };
  assign { _01_[3], _01_[1] } = { Sign_F_at_Abar[2], Sign_F_at_Abar[0] };
  assign { _00_[3], _00_[1] } = { Sign_F_at_A[2], Sign_F_at_A[0] };
endmodule

(* dynports =  1  *)
(* hdlname = "comparator" *)
(* src = "comparator.sv:1.1-47.10" *)
module \$paramod\comparator\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, Sign_Good, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar, Sign_F_at_C, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Det_A, Det_Abar, Det_B, Det_Bbar, Det_C, Det_Cbar
, Det_D, Det_Dbar, Det_X, Det_Xbar, Det_Y, Det_Ybar, num_detected);
  (* src = "comparator.sv:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "comparator.sv:2.20-2.24" *)
  input rstn;
  wire rstn;
  (* src = "comparator.sv:3.31-3.40" *)
  input [3:0] Sign_Good;
  wire [3:0] Sign_Good;
  (* src = "comparator.sv:5.32-5.43" *)
  input [3:0] Sign_F_at_A;
  wire [3:0] Sign_F_at_A;
  (* src = "comparator.sv:5.44-5.58" *)
  input [3:0] Sign_F_at_Abar;
  wire [3:0] Sign_F_at_Abar;
  (* src = "comparator.sv:6.9-6.20" *)
  input [3:0] Sign_F_at_B;
  wire [3:0] Sign_F_at_B;
  (* src = "comparator.sv:6.21-6.35" *)
  input [3:0] Sign_F_at_Bbar;
  wire [3:0] Sign_F_at_Bbar;
  (* src = "comparator.sv:7.9-7.20" *)
  input [3:0] Sign_F_at_C;
  wire [3:0] Sign_F_at_C;
  (* src = "comparator.sv:7.21-7.35" *)
  input [3:0] Sign_F_at_Cbar;
  wire [3:0] Sign_F_at_Cbar;
  (* src = "comparator.sv:8.9-8.20" *)
  input [3:0] Sign_F_at_D;
  wire [3:0] Sign_F_at_D;
  (* src = "comparator.sv:8.21-8.35" *)
  input [3:0] Sign_F_at_Dbar;
  wire [3:0] Sign_F_at_Dbar;
  (* src = "comparator.sv:9.9-9.20" *)
  input [3:0] Sign_F_at_X;
  wire [3:0] Sign_F_at_X;
  (* src = "comparator.sv:9.21-9.35" *)
  input [3:0] Sign_F_at_Xbar;
  wire [3:0] Sign_F_at_Xbar;
  (* src = "comparator.sv:10.9-10.20" *)
  input [3:0] Sign_F_at_Y;
  wire [3:0] Sign_F_at_Y;
  (* src = "comparator.sv:10.21-10.35" *)
  input [3:0] Sign_F_at_Ybar;
  wire [3:0] Sign_F_at_Ybar;
  (* src = "comparator.sv:12.18-12.23" *)
  output Det_A;
  wire Det_A;
  (* src = "comparator.sv:12.25-12.33" *)
  output Det_Abar;
  wire Det_Abar;
  (* src = "comparator.sv:13.9-13.14" *)
  output Det_B;
  wire Det_B;
  (* src = "comparator.sv:13.16-13.24" *)
  output Det_Bbar;
  wire Det_Bbar;
  (* src = "comparator.sv:14.9-14.14" *)
  output Det_C;
  wire Det_C;
  (* src = "comparator.sv:14.16-14.24" *)
  output Det_Cbar;
  wire Det_Cbar;
  (* src = "comparator.sv:15.9-15.14" *)
  output Det_D;
  wire Det_D;
  (* src = "comparator.sv:15.16-15.24" *)
  output Det_Dbar;
  wire Det_Dbar;
  (* src = "comparator.sv:16.9-16.14" *)
  output Det_X;
  wire Det_X;
  (* src = "comparator.sv:16.16-16.24" *)
  output Det_Xbar;
  wire Det_Xbar;
  (* src = "comparator.sv:17.9-17.14" *)
  output Det_Y;
  wire Det_Y;
  (* src = "comparator.sv:17.16-17.24" *)
  output Det_Ybar;
  wire Det_Ybar;
  (* src = "comparator.sv:18.22-18.34" *)
  output [3:0] num_detected;
  wire [3:0] num_detected;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  assign _085_ = ~(Sign_Good[0] ^ Sign_F_at_D[0]);
  assign _086_ = ~(Sign_Good[1] ^ Sign_F_at_D[1]);
  assign _087_ = _085_ & _086_;
  assign _088_ = ~(Sign_Good[3] ^ Sign_F_at_D[3]);
  assign _089_ = ~(Sign_Good[2] ^ Sign_F_at_D[2]);
  assign _090_ = _088_ & _089_;
  assign Det_D = ~(_087_ & _090_);
  assign _091_ = ~(Sign_Good[0] ^ Sign_F_at_X[0]);
  assign _092_ = ~(Sign_Good[1] ^ Sign_F_at_X[1]);
  assign _093_ = _091_ & _092_;
  assign _094_ = ~(Sign_Good[3] ^ Sign_F_at_X[3]);
  assign _095_ = ~(Sign_Good[2] ^ Sign_F_at_X[2]);
  assign _096_ = _094_ & _095_;
  assign Det_X = ~(_093_ & _096_);
  assign _097_ = ~(Sign_Good[0] ^ Sign_F_at_Y[0]);
  assign _098_ = ~(Sign_Good[1] ^ Sign_F_at_Y[1]);
  assign _099_ = _097_ & _098_;
  assign _100_ = ~(Sign_Good[3] ^ Sign_F_at_Y[3]);
  assign _101_ = ~(Sign_Good[2] ^ Sign_F_at_Y[2]);
  assign _102_ = _100_ & _101_;
  assign Det_Y = ~(_099_ & _102_);
  assign _103_ = ~(Sign_Good[0] ^ Sign_F_at_A[0]);
  assign _104_ = ~(Sign_Good[1] ^ Sign_F_at_A[1]);
  assign _105_ = _103_ & _104_;
  assign _106_ = ~(Sign_Good[3] ^ Sign_F_at_A[3]);
  assign _107_ = ~(Sign_Good[2] ^ Sign_F_at_A[2]);
  assign _108_ = _106_ & _107_;
  assign Det_A = ~(_105_ & _108_);
  assign _109_ = ~(Sign_Good[0] ^ Sign_F_at_Abar[0]);
  assign _110_ = ~(Sign_Good[1] ^ Sign_F_at_Abar[1]);
  assign _111_ = _109_ & _110_;
  assign _000_ = ~(Sign_Good[3] ^ Sign_F_at_Abar[3]);
  assign _001_ = ~(Sign_Good[2] ^ Sign_F_at_Abar[2]);
  assign _002_ = _000_ & _001_;
  assign Det_Abar = ~(_111_ & _002_);
  assign _003_ = ~(Det_A & Det_Abar);
  assign _004_ = ~(Sign_Good[0] ^ Sign_F_at_Bbar[0]);
  assign _005_ = ~(Sign_Good[1] ^ Sign_F_at_Bbar[1]);
  assign _006_ = _004_ & _005_;
  assign _007_ = ~(Sign_Good[3] ^ Sign_F_at_Bbar[3]);
  assign _008_ = ~(Sign_Good[2] ^ Sign_F_at_Bbar[2]);
  assign _009_ = _007_ & _008_;
  assign Det_Bbar = ~(_006_ & _009_);
  assign _010_ = Det_A ^ Det_Abar;
  assign _011_ = ~(Det_Bbar & _010_);
  assign _012_ = ~(_003_ & _011_);
  assign _013_ = Det_Bbar ^ _010_;
  assign _014_ = ~(Det_Y & _013_);
  assign _015_ = ~(Sign_Good[0] ^ Sign_F_at_Xbar[0]);
  assign _016_ = ~(Sign_Good[1] ^ Sign_F_at_Xbar[1]);
  assign _017_ = _015_ & _016_;
  assign _018_ = ~(Sign_Good[3] ^ Sign_F_at_Xbar[3]);
  assign _019_ = ~(Sign_Good[2] ^ Sign_F_at_Xbar[2]);
  assign _020_ = _018_ & _019_;
  assign Det_Xbar = ~(_017_ & _020_);
  assign _021_ = ~(Sign_Good[0] ^ Sign_F_at_Cbar[0]);
  assign _022_ = ~(Sign_Good[1] ^ Sign_F_at_Cbar[1]);
  assign _023_ = _021_ & _022_;
  assign _024_ = ~(Sign_Good[3] ^ Sign_F_at_Cbar[3]);
  assign _025_ = ~(Sign_Good[2] ^ Sign_F_at_Cbar[2]);
  assign _026_ = _024_ & _025_;
  assign Det_Cbar = ~(_023_ & _026_);
  assign _027_ = ~(Sign_Good[0] ^ Sign_F_at_Dbar[0]);
  assign _028_ = ~(Sign_Good[1] ^ Sign_F_at_Dbar[1]);
  assign _029_ = _027_ & _028_;
  assign _030_ = ~(Sign_Good[3] ^ Sign_F_at_Dbar[3]);
  assign _031_ = ~(Sign_Good[2] ^ Sign_F_at_Dbar[2]);
  assign _032_ = _030_ & _031_;
  assign Det_Dbar = ~(_029_ & _032_);
  assign _033_ = ~(Det_Cbar & Det_Dbar);
  assign _034_ = Det_Cbar ^ Det_Dbar;
  assign _035_ = ~(Det_Xbar & _034_);
  assign _036_ = Det_Xbar ^ _034_;
  assign _037_ = Det_Y ^ _013_;
  assign _038_ = ~(_036_ & _037_);
  assign _039_ = ~(_014_ & _038_);
  assign _040_ = ~(_012_ & _039_);
  assign _041_ = _036_ ^ _037_;
  assign _042_ = ~(Det_D & _041_);
  assign _043_ = Det_D ^ _041_;
  assign _044_ = ~(Det_X & _043_);
  assign _045_ = ~(_042_ & _044_);
  assign _046_ = ~(_033_ & _035_);
  assign _047_ = _012_ ^ _039_;
  assign _048_ = ~(_046_ & _047_);
  assign _049_ = _046_ ^ _047_;
  assign _050_ = ~(_045_ & _049_);
  assign _051_ = _040_ | _050_;
  assign _052_ = ~(Sign_Good[0] ^ Sign_F_at_C[0]);
  assign _053_ = ~(Sign_Good[1] ^ Sign_F_at_C[1]);
  assign _054_ = _052_ & _053_;
  assign _055_ = ~(Sign_Good[3] ^ Sign_F_at_C[3]);
  assign _056_ = ~(Sign_Good[2] ^ Sign_F_at_C[2]);
  assign _057_ = _055_ & _056_;
  assign Det_C = ~(_054_ & _057_);
  assign _058_ = Det_X ^ _043_;
  assign _059_ = ~(Det_C & _058_);
  assign _060_ = ~(Sign_F_at_Ybar[0] ^ Sign_Good[0]);
  assign _061_ = ~(Sign_F_at_Ybar[1] ^ Sign_Good[1]);
  assign _062_ = _060_ & _061_;
  assign _063_ = ~(Sign_F_at_Ybar[3] ^ Sign_Good[3]);
  assign _064_ = ~(Sign_F_at_Ybar[2] ^ Sign_Good[2]);
  assign _065_ = _063_ & _064_;
  assign Det_Ybar = ~(_062_ & _065_);
  assign _066_ = Det_C ^ _058_;
  assign _067_ = ~(Det_Ybar & _066_);
  assign _068_ = ~(_059_ & _067_);
  assign _069_ = _045_ ^ _049_;
  assign _070_ = ~(_068_ & _069_);
  assign _071_ = ~(Sign_Good[0] ^ Sign_F_at_B[0]);
  assign _072_ = ~(Sign_Good[1] ^ Sign_F_at_B[1]);
  assign _073_ = _071_ & _072_;
  assign _074_ = ~(Sign_Good[3] ^ Sign_F_at_B[3]);
  assign _075_ = ~(Sign_Good[2] ^ Sign_F_at_B[2]);
  assign _076_ = _074_ & _075_;
  assign Det_B = ~(_073_ & _076_);
  assign _077_ = Det_Ybar ^ _066_;
  assign _078_ = Det_B & _077_;
  assign _079_ = _068_ ^ _069_;
  assign _080_ = ~(_078_ & _079_);
  assign _081_ = ~(_070_ & _080_);
  assign _082_ = ~(_040_ & _048_);
  assign _083_ = _050_ ? _082_ : _040_;
  assign _084_ = ~(_081_ & _083_);
  assign num_detected[3] = ~(_051_ & _084_);
  assign num_detected[2] = _081_ ^ _083_;
  assign num_detected[0] = Det_B ^ _077_;
  assign num_detected[1] = _078_ ^ _079_;
endmodule

(* dynports =  1  *)
(* hdlname = "pattern_lfsr" *)
(* src = "pattern_gen.sv:1.1-21.10" *)
module \$paramod\pattern_lfsr\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, start, out);
  (* src = "pattern_gen.sv:4.34-4.37" *)
  input clk;
  wire clk;
  (* src = "pattern_gen.sv:5.34-5.38" *)
  input rstn;
  wire rstn;
  (* src = "pattern_gen.sv:6.17-6.22" *)
  input start;
  wire start;
  (* src = "pattern_gen.sv:7.34-7.37" *)
  output [3:0] out;
  reg [3:0] out;
  (* src = "pattern_gen.sv:10.11-10.19" *)
  wire feedback;
  assign feedback = out[3] ^ out[2];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[0] <= 1'h1;
    else if (start) out[0] <= out[1];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[1] <= 1'h0;
    else if (start) out[1] <= out[2];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[2] <= 1'h0;
    else if (start) out[2] <= out[3];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[3] <= 1'h0;
    else if (start) out[3] <= feedback;
endmodule

(* hdlname = "stuck_at_models" *)
(* src = "stuck_models.sv:3.1-64.10" *)
module \$paramod\stuck_at_models\REG_WIDTH=s32'00000000000000000000000000000100 (in, smodel, GoodF, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar);
  (* src = "stuck_models.sv:6.21-6.23" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "stuck_models.sv:7.22-7.28" *)
  input [3:0] smodel;
  wire [3:0] smodel;
  (* src = "stuck_models.sv:8.16-8.21" *)
  output GoodF;
  wire GoodF;
  (* src = "stuck_models.sv:9.16-9.22" *)
  output F_at_A;
  wire F_at_A;
  (* src = "stuck_models.sv:9.23-9.32" *)
  output F_at_Abar;
  wire F_at_Abar;
  (* src = "stuck_models.sv:10.16-10.22" *)
  output F_at_B;
  wire F_at_B;
  (* src = "stuck_models.sv:10.23-10.32" *)
  output F_at_Bbar;
  wire F_at_Bbar;
  (* src = "stuck_models.sv:11.16-11.22" *)
  output F_at_C;
  wire F_at_C;
  (* src = "stuck_models.sv:11.23-11.32" *)
  output F_at_Cbar;
  wire F_at_Cbar;
  (* src = "stuck_models.sv:12.16-12.22" *)
  output F_at_D;
  wire F_at_D;
  (* src = "stuck_models.sv:12.23-12.32" *)
  output F_at_Dbar;
  wire F_at_Dbar;
  (* src = "stuck_models.sv:13.16-13.22" *)
  output F_at_X;
  wire F_at_X;
  (* src = "stuck_models.sv:13.23-13.32" *)
  output F_at_Xbar;
  wire F_at_Xbar;
  (* src = "stuck_models.sv:14.16-14.22" *)
  output F_at_Y;
  wire F_at_Y;
  (* src = "stuck_models.sv:14.23-14.32" *)
  output F_at_Ybar;
  wire F_at_Ybar;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  assign _00_ = in[0] & in[1];
  assign _01_ = in[2] & in[3];
  assign _02_ = ~(_00_ | _01_);
  assign GoodF = ~_02_;
  assign _03_ = smodel[0] & smodel[1];
  assign _04_ = smodel[2] & ~(smodel[3]);
  assign _05_ = ~(_03_ & _04_);
  assign _06_ = _01_ & _05_;
  assign F_at_Dbar = _00_ | _06_;
  assign _07_ = smodel[0] & ~(smodel[1]);
  assign _08_ = smodel[3] & ~(smodel[2]);
  assign _09_ = ~(_07_ & _08_);
  assign _10_ = _00_ & _09_;
  assign F_at_Xbar = _01_ | _10_;
  assign _11_ = in[2] | _00_;
  assign _12_ = smodel[1] & ~(smodel[0]);
  assign _13_ = _04_ & _12_;
  assign _14_ = ~(_11_ & _13_);
  assign _15_ = in[3] | _00_;
  assign F_at_D = ~(_02_ & _14_);
  assign _16_ = ~(_08_ & _12_);
  assign F_at_Y = ~(_02_ & _16_);
  assign _17_ = ~(_04_ & _07_);
  assign _18_ = _01_ & _17_;
  assign F_at_Cbar = _00_ | _18_;
  assign _19_ = ~(_03_ & _08_);
  assign _20_ = _01_ & _19_;
  assign F_at_Ybar = _00_ | _20_;
  assign _21_ = ~(smodel[0] | smodel[1]);
  assign _22_ = _04_ & _21_;
  assign _23_ = ~(_15_ & _22_);
  assign F_at_C = ~(_02_ & _23_);
  assign _24_ = in[1] | _01_;
  assign _25_ = ~(smodel[2] | smodel[3]);
  assign _26_ = ~(_21_ & _25_);
  assign _27_ = ~(in[0] | _01_);
  assign _28_ = ~(_26_ & _27_);
  assign F_at_A = _24_ & _28_;
  assign _29_ = ~(_03_ & _25_);
  assign _30_ = _00_ & _29_;
  assign F_at_Bbar = _01_ | _30_;
  assign _31_ = ~(_12_ & _25_);
  assign _32_ = _31_ & ~(_24_);
  assign F_at_B = ~(_27_ | _32_);
  assign _33_ = ~(_07_ & _25_);
  assign _34_ = _00_ & _33_;
  assign F_at_Abar = _01_ | _34_;
  assign _35_ = ~(_08_ & _21_);
  assign F_at_X = ~(_02_ & _35_);
endmodule

(* dynports =  1  *)
(* src = "MISR.sv:1.1-77.10" *)
module MISR(clk, rstn, smodel, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar, GoodF, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar, Sign_F_at_C
, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Sign_Good);
  (* src = "MISR.sv:4.34-4.37" *)
  input clk;
  wire clk;
  (* src = "MISR.sv:5.34-5.38" *)
  input rstn;
  wire rstn;
  (* src = "MISR.sv:6.34-6.40" *)
  input [3:0] smodel;
  wire [3:0] smodel;
  (* src = "MISR.sv:7.18-7.24" *)
  input F_at_A;
  wire F_at_A;
  (* src = "MISR.sv:7.25-7.34" *)
  input F_at_Abar;
  wire F_at_Abar;
  (* src = "MISR.sv:8.17-8.23" *)
  input F_at_B;
  wire F_at_B;
  (* src = "MISR.sv:8.24-8.33" *)
  input F_at_Bbar;
  wire F_at_Bbar;
  (* src = "MISR.sv:9.17-9.23" *)
  input F_at_C;
  wire F_at_C;
  (* src = "MISR.sv:9.24-9.33" *)
  input F_at_Cbar;
  wire F_at_Cbar;
  (* src = "MISR.sv:10.17-10.23" *)
  input F_at_D;
  wire F_at_D;
  (* src = "MISR.sv:10.24-10.33" *)
  input F_at_Dbar;
  wire F_at_Dbar;
  (* src = "MISR.sv:11.17-11.23" *)
  input F_at_X;
  wire F_at_X;
  (* src = "MISR.sv:11.24-11.33" *)
  input F_at_Xbar;
  wire F_at_Xbar;
  (* src = "MISR.sv:12.17-12.23" *)
  input F_at_Y;
  wire F_at_Y;
  (* src = "MISR.sv:12.24-12.33" *)
  input F_at_Ybar;
  wire F_at_Ybar;
  (* src = "MISR.sv:13.17-13.22" *)
  input GoodF;
  wire GoodF;
  (* src = "MISR.sv:15.34-15.45" *)
  output [3:0] Sign_F_at_A;
  reg [3:0] Sign_F_at_A;
  (* src = "MISR.sv:15.46-15.60" *)
  output [3:0] Sign_F_at_Abar;
  reg [3:0] Sign_F_at_Abar;
  (* src = "MISR.sv:16.17-16.28" *)
  output [3:0] Sign_F_at_B;
  reg [3:0] Sign_F_at_B;
  (* src = "MISR.sv:16.29-16.43" *)
  output [3:0] Sign_F_at_Bbar;
  reg [3:0] Sign_F_at_Bbar;
  (* src = "MISR.sv:17.17-17.28" *)
  output [3:0] Sign_F_at_C;
  reg [3:0] Sign_F_at_C;
  (* src = "MISR.sv:17.29-17.43" *)
  output [3:0] Sign_F_at_Cbar;
  reg [3:0] Sign_F_at_Cbar;
  (* src = "MISR.sv:18.17-18.28" *)
  output [3:0] Sign_F_at_D;
  reg [3:0] Sign_F_at_D;
  (* src = "MISR.sv:18.29-18.43" *)
  output [3:0] Sign_F_at_Dbar;
  reg [3:0] Sign_F_at_Dbar;
  (* src = "MISR.sv:19.17-19.28" *)
  output [3:0] Sign_F_at_X;
  reg [3:0] Sign_F_at_X;
  (* src = "MISR.sv:19.29-19.43" *)
  output [3:0] Sign_F_at_Xbar;
  reg [3:0] Sign_F_at_Xbar;
  (* src = "MISR.sv:20.17-20.28" *)
  output [3:0] Sign_F_at_Y;
  reg [3:0] Sign_F_at_Y;
  (* src = "MISR.sv:20.29-20.43" *)
  output [3:0] Sign_F_at_Ybar;
  reg [3:0] Sign_F_at_Ybar;
  (* src = "MISR.sv:21.17-21.26" *)
  output [3:0] Sign_Good;
  reg [3:0] Sign_Good;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _00_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _01_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _02_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _03_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _04_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _05_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _06_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _07_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _08_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _09_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _10_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _11_;
  (* src = "MISR.sv:42.5-75.8" *)
  wire [3:0] _12_;
  assign _12_[2] = Sign_Good[1] ^ Sign_Good[3];
  assign _12_[0] = Sign_Good[3] ^ GoodF;
  assign _11_[2] = Sign_F_at_Ybar[1] ^ Sign_F_at_Ybar[3];
  assign _11_[0] = Sign_F_at_Ybar[3] ^ F_at_Ybar;
  assign _10_[2] = Sign_F_at_Y[1] ^ Sign_F_at_Y[3];
  assign _10_[0] = Sign_F_at_Y[3] ^ F_at_Y;
  assign _09_[2] = Sign_F_at_Xbar[1] ^ Sign_F_at_Xbar[3];
  assign _09_[0] = Sign_F_at_Xbar[3] ^ F_at_Xbar;
  assign _08_[2] = Sign_F_at_X[1] ^ Sign_F_at_X[3];
  assign _08_[0] = Sign_F_at_X[3] ^ F_at_X;
  assign _07_[2] = Sign_F_at_Dbar[1] ^ Sign_F_at_Dbar[3];
  assign _07_[0] = Sign_F_at_Dbar[3] ^ F_at_Dbar;
  assign _06_[2] = Sign_F_at_D[1] ^ Sign_F_at_D[3];
  assign _06_[0] = Sign_F_at_D[3] ^ F_at_D;
  assign _05_[2] = Sign_F_at_Cbar[1] ^ Sign_F_at_Cbar[3];
  assign _05_[0] = Sign_F_at_Cbar[3] ^ F_at_Cbar;
  assign _04_[2] = Sign_F_at_C[1] ^ Sign_F_at_C[3];
  assign _04_[0] = Sign_F_at_C[3] ^ F_at_C;
  assign _03_[2] = Sign_F_at_Bbar[1] ^ Sign_F_at_Bbar[3];
  assign _03_[0] = Sign_F_at_Bbar[3] ^ F_at_Bbar;
  assign _02_[2] = Sign_F_at_B[1] ^ Sign_F_at_B[3];
  assign _02_[0] = Sign_F_at_B[3] ^ F_at_B;
  assign _01_[2] = Sign_F_at_Abar[1] ^ Sign_F_at_Abar[3];
  assign _01_[0] = Sign_F_at_Abar[3] ^ F_at_Abar;
  assign _00_[2] = Sign_F_at_A[1] ^ Sign_F_at_A[3];
  assign _00_[0] = Sign_F_at_A[3] ^ F_at_A;
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[0] <= 1'h0;
    else Sign_F_at_A[0] <= _00_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[1] <= 1'h0;
    else Sign_F_at_A[1] <= Sign_F_at_A[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[2] <= 1'h0;
    else Sign_F_at_A[2] <= _00_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_A[3] <= 1'h1;
    else Sign_F_at_A[3] <= Sign_F_at_A[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[0] <= 1'h0;
    else Sign_F_at_Abar[0] <= _01_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[1] <= 1'h0;
    else Sign_F_at_Abar[1] <= Sign_F_at_Abar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[2] <= 1'h0;
    else Sign_F_at_Abar[2] <= _01_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Abar[3] <= 1'h1;
    else Sign_F_at_Abar[3] <= Sign_F_at_Abar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[0] <= 1'h0;
    else Sign_F_at_B[0] <= _02_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[1] <= 1'h0;
    else Sign_F_at_B[1] <= Sign_F_at_B[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[2] <= 1'h0;
    else Sign_F_at_B[2] <= _02_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_B[3] <= 1'h1;
    else Sign_F_at_B[3] <= Sign_F_at_B[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[0] <= 1'h0;
    else Sign_F_at_Bbar[0] <= _03_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[1] <= 1'h0;
    else Sign_F_at_Bbar[1] <= Sign_F_at_Bbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[2] <= 1'h0;
    else Sign_F_at_Bbar[2] <= _03_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Bbar[3] <= 1'h1;
    else Sign_F_at_Bbar[3] <= Sign_F_at_Bbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[0] <= 1'h0;
    else Sign_F_at_C[0] <= _04_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[1] <= 1'h0;
    else Sign_F_at_C[1] <= Sign_F_at_C[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[2] <= 1'h0;
    else Sign_F_at_C[2] <= _04_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_C[3] <= 1'h1;
    else Sign_F_at_C[3] <= Sign_F_at_C[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[0] <= 1'h0;
    else Sign_F_at_Cbar[0] <= _05_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[1] <= 1'h0;
    else Sign_F_at_Cbar[1] <= Sign_F_at_Cbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[2] <= 1'h0;
    else Sign_F_at_Cbar[2] <= _05_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Cbar[3] <= 1'h1;
    else Sign_F_at_Cbar[3] <= Sign_F_at_Cbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[0] <= 1'h0;
    else Sign_F_at_D[0] <= _06_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[1] <= 1'h0;
    else Sign_F_at_D[1] <= Sign_F_at_D[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[2] <= 1'h0;
    else Sign_F_at_D[2] <= _06_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_D[3] <= 1'h1;
    else Sign_F_at_D[3] <= Sign_F_at_D[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[0] <= 1'h0;
    else Sign_F_at_Dbar[0] <= _07_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[1] <= 1'h0;
    else Sign_F_at_Dbar[1] <= Sign_F_at_Dbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[2] <= 1'h0;
    else Sign_F_at_Dbar[2] <= _07_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Dbar[3] <= 1'h1;
    else Sign_F_at_Dbar[3] <= Sign_F_at_Dbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[0] <= 1'h0;
    else Sign_F_at_X[0] <= _08_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[1] <= 1'h0;
    else Sign_F_at_X[1] <= Sign_F_at_X[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[2] <= 1'h0;
    else Sign_F_at_X[2] <= _08_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_X[3] <= 1'h1;
    else Sign_F_at_X[3] <= Sign_F_at_X[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[0] <= 1'h0;
    else Sign_F_at_Xbar[0] <= _09_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[1] <= 1'h0;
    else Sign_F_at_Xbar[1] <= Sign_F_at_Xbar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[2] <= 1'h0;
    else Sign_F_at_Xbar[2] <= _09_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Xbar[3] <= 1'h1;
    else Sign_F_at_Xbar[3] <= Sign_F_at_Xbar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[0] <= 1'h0;
    else Sign_F_at_Y[0] <= _10_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[1] <= 1'h0;
    else Sign_F_at_Y[1] <= Sign_F_at_Y[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[2] <= 1'h0;
    else Sign_F_at_Y[2] <= _10_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Y[3] <= 1'h1;
    else Sign_F_at_Y[3] <= Sign_F_at_Y[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[0] <= 1'h0;
    else Sign_F_at_Ybar[0] <= _11_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[1] <= 1'h0;
    else Sign_F_at_Ybar[1] <= Sign_F_at_Ybar[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[2] <= 1'h0;
    else Sign_F_at_Ybar[2] <= _11_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_F_at_Ybar[3] <= 1'h1;
    else Sign_F_at_Ybar[3] <= Sign_F_at_Ybar[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[0] <= 1'h0;
    else Sign_Good[0] <= _12_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[1] <= 1'h0;
    else Sign_Good[1] <= Sign_Good[0];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[2] <= 1'h0;
    else Sign_Good[2] <= _12_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "MISR.sv:42.5-75.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) Sign_Good[3] <= 1'h1;
    else Sign_Good[3] <= Sign_Good[2];
  assign { _12_[3], _12_[1] } = { Sign_Good[2], Sign_Good[0] };
  assign { _11_[3], _11_[1] } = { Sign_F_at_Ybar[2], Sign_F_at_Ybar[0] };
  assign { _10_[3], _10_[1] } = { Sign_F_at_Y[2], Sign_F_at_Y[0] };
  assign { _09_[3], _09_[1] } = { Sign_F_at_Xbar[2], Sign_F_at_Xbar[0] };
  assign { _08_[3], _08_[1] } = { Sign_F_at_X[2], Sign_F_at_X[0] };
  assign { _07_[3], _07_[1] } = { Sign_F_at_Dbar[2], Sign_F_at_Dbar[0] };
  assign { _06_[3], _06_[1] } = { Sign_F_at_D[2], Sign_F_at_D[0] };
  assign { _05_[3], _05_[1] } = { Sign_F_at_Cbar[2], Sign_F_at_Cbar[0] };
  assign { _04_[3], _04_[1] } = { Sign_F_at_C[2], Sign_F_at_C[0] };
  assign { _03_[3], _03_[1] } = { Sign_F_at_Bbar[2], Sign_F_at_Bbar[0] };
  assign { _02_[3], _02_[1] } = { Sign_F_at_B[2], Sign_F_at_B[0] };
  assign { _01_[3], _01_[1] } = { Sign_F_at_Abar[2], Sign_F_at_Abar[0] };
  assign { _00_[3], _00_[1] } = { Sign_F_at_A[2], Sign_F_at_A[0] };
endmodule

(* dynports =  1  *)
(* src = "top.sv:9.1-147.10" *)
module bist_top(rstn, clk, start_ext, smodel, out_pattern, cut_out, done, pass, coverage, num_detected);
  (* src = "top.sv:14.37-14.41" *)
  input rstn;
  wire rstn;
  (* src = "top.sv:14.43-14.46" *)
  input clk;
  wire clk;
  (* src = "top.sv:15.37-15.46" *)
  input start_ext;
  wire start_ext;
  (* src = "top.sv:16.37-16.43" *)
  input [3:0] smodel;
  wire [3:0] smodel;
  (* src = "top.sv:18.37-18.48" *)
  output [3:0] out_pattern;
  wire [3:0] out_pattern;
  (* src = "top.sv:19.37-19.44" *)
  output cut_out;
  wire cut_out;
  (* src = "top.sv:20.37-20.41" *)
  output done;
  wire done;
  (* src = "top.sv:20.43-20.47" *)
  output pass;
  wire pass;
  (* src = "top.sv:21.37-21.45" *)
  output [6:0] coverage;
  wire [6:0] coverage;
  (* src = "top.sv:22.37-22.49" *)
  output [3:0] num_detected;
  wire [3:0] num_detected;
  (* src = "top.sv:44.11-44.16" *)
  wire Det_A;
  (* src = "top.sv:44.18-44.26" *)
  wire Det_Abar;
  (* src = "top.sv:45.11-45.16" *)
  wire Det_B;
  (* src = "top.sv:45.18-45.26" *)
  wire Det_Bbar;
  (* src = "top.sv:46.11-46.16" *)
  wire Det_C;
  (* src = "top.sv:46.18-46.26" *)
  wire Det_Cbar;
  (* src = "top.sv:47.11-47.16" *)
  wire Det_D;
  (* src = "top.sv:47.18-47.26" *)
  wire Det_Dbar;
  (* src = "top.sv:48.11-48.16" *)
  wire Det_X;
  (* src = "top.sv:48.18-48.26" *)
  wire Det_Xbar;
  (* src = "top.sv:49.11-49.16" *)
  wire Det_Y;
  (* src = "top.sv:49.18-49.26" *)
  wire Det_Ybar;
  (* src = "top.sv:26.11-26.17" *)
  wire F_at_A;
  (* src = "top.sv:26.19-26.28" *)
  wire F_at_Abar;
  (* src = "top.sv:27.11-27.17" *)
  wire F_at_B;
  (* src = "top.sv:27.19-27.28" *)
  wire F_at_Bbar;
  (* src = "top.sv:28.11-28.17" *)
  wire F_at_C;
  (* src = "top.sv:28.19-28.28" *)
  wire F_at_Cbar;
  (* src = "top.sv:29.11-29.17" *)
  wire F_at_D;
  (* src = "top.sv:29.19-29.28" *)
  wire F_at_Dbar;
  (* src = "top.sv:30.11-30.17" *)
  wire F_at_X;
  (* src = "top.sv:30.19-30.28" *)
  wire F_at_Xbar;
  (* src = "top.sv:31.11-31.17" *)
  wire F_at_Y;
  (* src = "top.sv:31.19-31.28" *)
  wire F_at_Ybar;
  (* src = "top.sv:32.11-32.16" *)
  wire GoodF;
  (* src = "top.sv:35.27-35.38" *)
  wire [3:0] Sign_F_at_A;
  (* src = "top.sv:35.40-35.54" *)
  wire [3:0] Sign_F_at_Abar;
  (* src = "top.sv:36.27-36.38" *)
  wire [3:0] Sign_F_at_B;
  (* src = "top.sv:36.40-36.54" *)
  wire [3:0] Sign_F_at_Bbar;
  (* src = "top.sv:37.27-37.38" *)
  wire [3:0] Sign_F_at_C;
  (* src = "top.sv:37.40-37.54" *)
  wire [3:0] Sign_F_at_Cbar;
  (* src = "top.sv:38.27-38.38" *)
  wire [3:0] Sign_F_at_D;
  (* src = "top.sv:38.40-38.54" *)
  wire [3:0] Sign_F_at_Dbar;
  (* src = "top.sv:39.27-39.38" *)
  wire [3:0] Sign_F_at_X;
  (* src = "top.sv:39.40-39.54" *)
  wire [3:0] Sign_F_at_Xbar;
  (* src = "top.sv:40.27-40.38" *)
  wire [3:0] Sign_F_at_Y;
  (* src = "top.sv:40.40-40.54" *)
  wire [3:0] Sign_F_at_Ybar;
  (* src = "top.sv:41.27-41.36" *)
  wire [3:0] Sign_Good;
  (* src = "top.sv:53.20-53.30" *)
  wire capture_en;
  (* src = "top.sv:53.11-53.18" *)
  wire scan_en;
  (* src = "top.sv:52.11-52.16" *)
  wire start;
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:57.9-60.6" *)
  cut u_cut (
    .in(out_pattern),
    .out(cut_out)
  );
  (* src = "top.sv:110.7-127.8" *)
  \$paramod\comparator\REG_WIDTH=s32'00000000000000000000000000000100  uut_comp (
    .Det_A(Det_A),
    .Det_Abar(Det_Abar),
    .Det_B(Det_B),
    .Det_Bbar(Det_Bbar),
    .Det_C(Det_C),
    .Det_Cbar(Det_Cbar),
    .Det_D(Det_D),
    .Det_Dbar(Det_Dbar),
    .Det_X(Det_X),
    .Det_Xbar(Det_Xbar),
    .Det_Y(Det_Y),
    .Det_Ybar(Det_Ybar),
    .Sign_F_at_A(Sign_F_at_A),
    .Sign_F_at_Abar(Sign_F_at_Abar),
    .Sign_F_at_B(Sign_F_at_B),
    .Sign_F_at_Bbar(Sign_F_at_Bbar),
    .Sign_F_at_C(Sign_F_at_C),
    .Sign_F_at_Cbar(Sign_F_at_Cbar),
    .Sign_F_at_D(Sign_F_at_D),
    .Sign_F_at_Dbar(Sign_F_at_Dbar),
    .Sign_F_at_X(Sign_F_at_X),
    .Sign_F_at_Xbar(Sign_F_at_Xbar),
    .Sign_F_at_Y(Sign_F_at_Y),
    .Sign_F_at_Ybar(Sign_F_at_Ybar),
    .Sign_Good(Sign_Good),
    .clk(clk),
    .num_detected(num_detected),
    .rstn(rstn)
  );
  (* src = "top.sv:134.5-145.6" *)
  \$paramod$5a749a99f52c3c2473bfdf42ed69512a64c0e60e\controller  uut_controller (
    .capture_en(capture_en),
    .clk(clk),
    .coverage(coverage),
    .done(done),
    .num_detected(num_detected),
    .pass(pass),
    .rstn(rstn),
    .scan_en(scan_en),
    .start(start),
    .start_ext(start_ext)
  );
  (* src = "top.sv:87.7-106.8" *)
  \$paramod\MISR\REG_WIDTH=s32'00000000000000000000000000000100  uut_misr (
    .F_at_A(F_at_A),
    .F_at_Abar(F_at_Abar),
    .F_at_B(F_at_B),
    .F_at_Bbar(F_at_Bbar),
    .F_at_C(F_at_C),
    .F_at_Cbar(F_at_Cbar),
    .F_at_D(F_at_D),
    .F_at_Dbar(F_at_Dbar),
    .F_at_X(F_at_X),
    .F_at_Xbar(F_at_Xbar),
    .F_at_Y(F_at_Y),
    .F_at_Ybar(F_at_Ybar),
    .GoodF(GoodF),
    .Sign_F_at_A(Sign_F_at_A),
    .Sign_F_at_Abar(Sign_F_at_Abar),
    .Sign_F_at_B(Sign_F_at_B),
    .Sign_F_at_Bbar(Sign_F_at_Bbar),
    .Sign_F_at_C(Sign_F_at_C),
    .Sign_F_at_Cbar(Sign_F_at_Cbar),
    .Sign_F_at_D(Sign_F_at_D),
    .Sign_F_at_Dbar(Sign_F_at_Dbar),
    .Sign_F_at_X(Sign_F_at_X),
    .Sign_F_at_Xbar(Sign_F_at_Xbar),
    .Sign_F_at_Y(Sign_F_at_Y),
    .Sign_F_at_Ybar(Sign_F_at_Ybar),
    .Sign_Good(Sign_Good),
    .clk(clk),
    .rstn(rstn),
    .smodel(smodel)
  );
  (* src = "top.sv:64.7-74.8" *)
  \$paramod\stuck_at_models\REG_WIDTH=s32'00000000000000000000000000000100  uut_model (
    .F_at_A(F_at_A),
    .F_at_Abar(F_at_Abar),
    .F_at_B(F_at_B),
    .F_at_Bbar(F_at_Bbar),
    .F_at_C(F_at_C),
    .F_at_Cbar(F_at_Cbar),
    .F_at_D(F_at_D),
    .F_at_Dbar(F_at_Dbar),
    .F_at_X(F_at_X),
    .F_at_Xbar(F_at_Xbar),
    .F_at_Y(F_at_Y),
    .F_at_Ybar(F_at_Ybar),
    .GoodF(GoodF),
    .in(out_pattern),
    .smodel(smodel)
  );
  (* src = "top.sv:78.7-83.8" *)
  \$paramod\pattern_lfsr\REG_WIDTH=s32'00000000000000000000000000000100  uut_pattern (
    .clk(clk),
    .out(out_pattern),
    .rstn(rstn),
    .start(start)
  );
endmodule

(* dynports =  1  *)
(* src = "comparator.sv:1.1-47.10" *)
module comparator(clk, rstn, Sign_Good, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar, Sign_F_at_C, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Det_A, Det_Abar, Det_B, Det_Bbar, Det_C, Det_Cbar
, Det_D, Det_Dbar, Det_X, Det_Xbar, Det_Y, Det_Ybar, num_detected);
  (* src = "comparator.sv:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "comparator.sv:2.20-2.24" *)
  input rstn;
  wire rstn;
  (* src = "comparator.sv:3.31-3.40" *)
  input [3:0] Sign_Good;
  wire [3:0] Sign_Good;
  (* src = "comparator.sv:5.32-5.43" *)
  input [3:0] Sign_F_at_A;
  wire [3:0] Sign_F_at_A;
  (* src = "comparator.sv:5.44-5.58" *)
  input [3:0] Sign_F_at_Abar;
  wire [3:0] Sign_F_at_Abar;
  (* src = "comparator.sv:6.9-6.20" *)
  input [3:0] Sign_F_at_B;
  wire [3:0] Sign_F_at_B;
  (* src = "comparator.sv:6.21-6.35" *)
  input [3:0] Sign_F_at_Bbar;
  wire [3:0] Sign_F_at_Bbar;
  (* src = "comparator.sv:7.9-7.20" *)
  input [3:0] Sign_F_at_C;
  wire [3:0] Sign_F_at_C;
  (* src = "comparator.sv:7.21-7.35" *)
  input [3:0] Sign_F_at_Cbar;
  wire [3:0] Sign_F_at_Cbar;
  (* src = "comparator.sv:8.9-8.20" *)
  input [3:0] Sign_F_at_D;
  wire [3:0] Sign_F_at_D;
  (* src = "comparator.sv:8.21-8.35" *)
  input [3:0] Sign_F_at_Dbar;
  wire [3:0] Sign_F_at_Dbar;
  (* src = "comparator.sv:9.9-9.20" *)
  input [3:0] Sign_F_at_X;
  wire [3:0] Sign_F_at_X;
  (* src = "comparator.sv:9.21-9.35" *)
  input [3:0] Sign_F_at_Xbar;
  wire [3:0] Sign_F_at_Xbar;
  (* src = "comparator.sv:10.9-10.20" *)
  input [3:0] Sign_F_at_Y;
  wire [3:0] Sign_F_at_Y;
  (* src = "comparator.sv:10.21-10.35" *)
  input [3:0] Sign_F_at_Ybar;
  wire [3:0] Sign_F_at_Ybar;
  (* src = "comparator.sv:12.18-12.23" *)
  output Det_A;
  wire Det_A;
  (* src = "comparator.sv:12.25-12.33" *)
  output Det_Abar;
  wire Det_Abar;
  (* src = "comparator.sv:13.9-13.14" *)
  output Det_B;
  wire Det_B;
  (* src = "comparator.sv:13.16-13.24" *)
  output Det_Bbar;
  wire Det_Bbar;
  (* src = "comparator.sv:14.9-14.14" *)
  output Det_C;
  wire Det_C;
  (* src = "comparator.sv:14.16-14.24" *)
  output Det_Cbar;
  wire Det_Cbar;
  (* src = "comparator.sv:15.9-15.14" *)
  output Det_D;
  wire Det_D;
  (* src = "comparator.sv:15.16-15.24" *)
  output Det_Dbar;
  wire Det_Dbar;
  (* src = "comparator.sv:16.9-16.14" *)
  output Det_X;
  wire Det_X;
  (* src = "comparator.sv:16.16-16.24" *)
  output Det_Xbar;
  wire Det_Xbar;
  (* src = "comparator.sv:17.9-17.14" *)
  output Det_Y;
  wire Det_Y;
  (* src = "comparator.sv:17.16-17.24" *)
  output Det_Ybar;
  wire Det_Ybar;
  (* src = "comparator.sv:18.22-18.34" *)
  output [3:0] num_detected;
  wire [3:0] num_detected;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  assign _085_ = ~(Sign_Good[0] ^ Sign_F_at_C[0]);
  assign _086_ = ~(Sign_Good[1] ^ Sign_F_at_C[1]);
  assign _087_ = _085_ & _086_;
  assign _088_ = ~(Sign_Good[3] ^ Sign_F_at_C[3]);
  assign _089_ = ~(Sign_Good[2] ^ Sign_F_at_C[2]);
  assign _090_ = _088_ & _089_;
  assign Det_C = ~(_087_ & _090_);
  assign _091_ = ~(Sign_Good[0] ^ Sign_F_at_A[0]);
  assign _092_ = ~(Sign_Good[1] ^ Sign_F_at_A[1]);
  assign _093_ = _091_ & _092_;
  assign _094_ = ~(Sign_Good[3] ^ Sign_F_at_A[3]);
  assign _095_ = ~(Sign_Good[2] ^ Sign_F_at_A[2]);
  assign _096_ = _094_ & _095_;
  assign Det_A = ~(_093_ & _096_);
  assign _097_ = ~(Sign_Good[0] ^ Sign_F_at_Abar[0]);
  assign _098_ = ~(Sign_Good[1] ^ Sign_F_at_Abar[1]);
  assign _099_ = _097_ & _098_;
  assign _100_ = ~(Sign_Good[3] ^ Sign_F_at_Abar[3]);
  assign _101_ = ~(Sign_Good[2] ^ Sign_F_at_Abar[2]);
  assign _102_ = _100_ & _101_;
  assign Det_Abar = ~(_099_ & _102_);
  assign _103_ = ~(Det_A & Det_Abar);
  assign _104_ = ~(Sign_Good[0] ^ Sign_F_at_Bbar[0]);
  assign _105_ = ~(Sign_Good[1] ^ Sign_F_at_Bbar[1]);
  assign _106_ = _104_ & _105_;
  assign _107_ = ~(Sign_Good[3] ^ Sign_F_at_Bbar[3]);
  assign _108_ = ~(Sign_Good[2] ^ Sign_F_at_Bbar[2]);
  assign _109_ = _107_ & _108_;
  assign Det_Bbar = ~(_106_ & _109_);
  assign _110_ = Det_A ^ Det_Abar;
  assign _111_ = ~(Det_Bbar & _110_);
  assign _000_ = ~(_103_ & _111_);
  assign _001_ = ~(Sign_Good[0] ^ Sign_F_at_Y[0]);
  assign _002_ = ~(Sign_Good[1] ^ Sign_F_at_Y[1]);
  assign _003_ = _001_ & _002_;
  assign _004_ = ~(Sign_Good[3] ^ Sign_F_at_Y[3]);
  assign _005_ = ~(Sign_Good[2] ^ Sign_F_at_Y[2]);
  assign _006_ = _004_ & _005_;
  assign Det_Y = ~(_003_ & _006_);
  assign _007_ = Det_Bbar ^ _110_;
  assign _008_ = ~(Det_Y & _007_);
  assign _009_ = ~(Sign_Good[0] ^ Sign_F_at_Xbar[0]);
  assign _010_ = ~(Sign_Good[1] ^ Sign_F_at_Xbar[1]);
  assign _011_ = _009_ & _010_;
  assign _012_ = ~(Sign_Good[3] ^ Sign_F_at_Xbar[3]);
  assign _013_ = ~(Sign_Good[2] ^ Sign_F_at_Xbar[2]);
  assign _014_ = _012_ & _013_;
  assign Det_Xbar = ~(_011_ & _014_);
  assign _015_ = ~(Sign_Good[0] ^ Sign_F_at_Cbar[0]);
  assign _016_ = ~(Sign_Good[1] ^ Sign_F_at_Cbar[1]);
  assign _017_ = _015_ & _016_;
  assign _018_ = ~(Sign_Good[3] ^ Sign_F_at_Cbar[3]);
  assign _019_ = ~(Sign_Good[2] ^ Sign_F_at_Cbar[2]);
  assign _020_ = _018_ & _019_;
  assign Det_Cbar = ~(_017_ & _020_);
  assign _021_ = ~(Sign_Good[0] ^ Sign_F_at_Dbar[0]);
  assign _022_ = ~(Sign_Good[1] ^ Sign_F_at_Dbar[1]);
  assign _023_ = _021_ & _022_;
  assign _024_ = ~(Sign_Good[3] ^ Sign_F_at_Dbar[3]);
  assign _025_ = ~(Sign_Good[2] ^ Sign_F_at_Dbar[2]);
  assign _026_ = _024_ & _025_;
  assign Det_Dbar = ~(_023_ & _026_);
  assign _027_ = ~(Det_Cbar & Det_Dbar);
  assign _028_ = Det_Cbar ^ Det_Dbar;
  assign _029_ = ~(Det_Xbar & _028_);
  assign _030_ = Det_Xbar ^ _028_;
  assign _031_ = Det_Y ^ _007_;
  assign _032_ = ~(_030_ & _031_);
  assign _033_ = ~(_008_ & _032_);
  assign _034_ = ~(_000_ & _033_);
  assign _035_ = ~(_027_ & _029_);
  assign _036_ = _000_ ^ _033_;
  assign _037_ = ~(_035_ & _036_);
  assign _038_ = ~(_034_ & _037_);
  assign _039_ = ~(Sign_Good[0] ^ Sign_F_at_D[0]);
  assign _040_ = ~(Sign_Good[1] ^ Sign_F_at_D[1]);
  assign _041_ = _039_ & _040_;
  assign _042_ = ~(Sign_Good[3] ^ Sign_F_at_D[3]);
  assign _043_ = ~(Sign_Good[2] ^ Sign_F_at_D[2]);
  assign _044_ = _042_ & _043_;
  assign Det_D = ~(_041_ & _044_);
  assign _045_ = _030_ ^ _031_;
  assign _046_ = ~(Det_D & _045_);
  assign _047_ = ~(Sign_Good[0] ^ Sign_F_at_X[0]);
  assign _048_ = ~(Sign_Good[1] ^ Sign_F_at_X[1]);
  assign _049_ = _047_ & _048_;
  assign _050_ = ~(Sign_Good[3] ^ Sign_F_at_X[3]);
  assign _051_ = ~(Sign_Good[2] ^ Sign_F_at_X[2]);
  assign _052_ = _050_ & _051_;
  assign Det_X = ~(_049_ & _052_);
  assign _053_ = Det_D ^ _045_;
  assign _054_ = ~(Det_X & _053_);
  assign _055_ = ~(_046_ & _054_);
  assign _056_ = _035_ ^ _036_;
  assign _057_ = _055_ & _056_;
  assign _058_ = ~(_038_ & _057_);
  assign _059_ = Det_X ^ _053_;
  assign _060_ = ~(Det_C & _059_);
  assign _061_ = ~(Sign_F_at_Ybar[0] ^ Sign_Good[0]);
  assign _062_ = ~(Sign_F_at_Ybar[1] ^ Sign_Good[1]);
  assign _063_ = _061_ & _062_;
  assign _064_ = ~(Sign_F_at_Ybar[3] ^ Sign_Good[3]);
  assign _065_ = ~(Sign_F_at_Ybar[2] ^ Sign_Good[2]);
  assign _066_ = _064_ & _065_;
  assign Det_Ybar = ~(_063_ & _066_);
  assign _067_ = Det_C ^ _059_;
  assign _068_ = ~(Det_Ybar & _067_);
  assign _069_ = ~(_060_ & _068_);
  assign _070_ = _055_ ^ _056_;
  assign _071_ = ~(_069_ & _070_);
  assign _072_ = ~(Sign_Good[0] ^ Sign_F_at_B[0]);
  assign _073_ = ~(Sign_Good[1] ^ Sign_F_at_B[1]);
  assign _074_ = _072_ & _073_;
  assign _075_ = ~(Sign_Good[3] ^ Sign_F_at_B[3]);
  assign _076_ = ~(Sign_Good[2] ^ Sign_F_at_B[2]);
  assign _077_ = _075_ & _076_;
  assign Det_B = ~(_074_ & _077_);
  assign _078_ = Det_Ybar ^ _067_;
  assign _079_ = Det_B & _078_;
  assign _080_ = _069_ ^ _070_;
  assign _081_ = ~(_079_ & _080_);
  assign _082_ = ~(_071_ & _081_);
  assign _083_ = _038_ ^ _057_;
  assign _084_ = ~(_082_ & _083_);
  assign num_detected[3] = ~(_058_ & _084_);
  assign num_detected[0] = Det_B ^ _078_;
  assign num_detected[1] = _079_ ^ _080_;
  assign num_detected[2] = _082_ ^ _083_;
endmodule

(* src = "controller.sv:3.1-149.10" *)
module controller(clk, rstn, start_ext, num_detected, start, scan_en, capture_en, done, pass, coverage);
  (* src = "controller.sv:7.24-7.27" *)
  input clk;
  wire clk;
  (* src = "controller.sv:8.24-8.28" *)
  input rstn;
  wire rstn;
  (* src = "controller.sv:11.24-11.33" *)
  input start_ext;
  wire start_ext;
  (* src = "controller.sv:14.24-14.36" *)
  input [3:0] num_detected;
  wire [3:0] num_detected;
  (* src = "controller.sv:17.24-17.29" *)
  output start;
  wire start;
  (* src = "controller.sv:20.24-20.31" *)
  output scan_en;
  wire scan_en;
  (* src = "controller.sv:21.24-21.34" *)
  output capture_en;
  wire capture_en;
  (* src = "controller.sv:24.24-24.28" *)
  output done;
  wire done;
  (* src = "controller.sv:25.24-25.28" *)
  output pass;
  wire pass;
  (* src = "controller.sv:26.24-26.32" *)
  output [6:0] coverage;
  wire [6:0] coverage;
  (* src = "controller.sv:111.5-143.8" *)
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "controller.sv:139.34-139.62" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* force_downto = 32'd1 *)
  (* src = "controller.sv:140.33-140.68|/opt/homebrew/bin/../share/yosys/techmap.v:400.23-400.24" *)
  wire [31:0] _32_;
  (* src = "controller.sv:39.17-39.29" *)
  reg [6:0] coverage_reg;
  (* src = "controller.sv:37.17-37.26" *)
  reg [4:0] cycle_cnt;
  (* src = "controller.sv:38.17-38.25" *)
  reg pass_reg;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  assign _07_ = ~num_detected[3];
  assign _32_[2] = num_detected[2] & num_detected[3];
  assign _08_ = num_detected[2] & ~(num_detected[1]);
  assign _09_ = num_detected[2] ? num_detected[1] : num_detected[3];
  assign _32_[1] = _09_ & ~(_32_[2]);
  assign _10_ = num_detected[3] & _08_;
  assign _11_ = num_detected[0] | num_detected[3];
  assign _12_ = num_detected[1] & ~(num_detected[2]);
  assign _13_ = ~(num_detected[0] & num_detected[3]);
  assign _14_ = ~(_11_ & _12_);
  assign _15_ = ~(_13_ & _14_);
  assign _32_[0] = _08_ ? _07_ : _15_;
  assign _16_ = cycle_cnt[3] & cycle_cnt[2];
  assign _17_ = ~(cycle_cnt[0] | cycle_cnt[4]);
  assign _18_ = cycle_cnt[1] & _17_;
  assign _19_ = ~(_16_ & _18_);
  assign _20_ = state[2] & _19_;
  assign _21_ = cycle_cnt[0] & cycle_cnt[1];
  assign _22_ = ~(cycle_cnt[2] & _21_);
  assign _23_ = _16_ & _21_;
  assign _24_ = ~(cycle_cnt[3] ^ _22_);
  assign _00_[3] = _20_ & _24_;
  assign _25_ = cycle_cnt[2] ^ _21_;
  assign _00_[2] = _20_ & _25_;
  assign _26_ = cycle_cnt[0] ^ cycle_cnt[1];
  assign _00_[1] = _20_ & _26_;
  assign _00_[0] = _20_ & ~(cycle_cnt[0]);
  assign _01_ = state[0] & ~(start_ext);
  assign _27_ = state[0] | state[3];
  assign _28_ = start_ext & _27_;
  assign _03_ = _20_ | _28_;
  assign _29_ = state[3] & ~(start_ext);
  assign _05_ = state[1] | state[3];
  assign _04_ = state[1] | _29_;
  assign _30_ = ~(state[2] | state[0]);
  assign done = _30_ & ~(state[1]);
  assign _31_ = ~(cycle_cnt[4] ^ _23_);
  assign _00_[4] = state[2] & ~(_31_);
  assign _06_ = _10_ & ~(num_detected[0]);
  assign _02_ = state[2] & ~(_19_);
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) pass_reg <= 1'h0;
    else if (state[1]) pass_reg <= _06_;
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[0] <= 1'h0;
    else if (state[1]) coverage_reg[0] <= _32_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[1] <= 1'h0;
    else if (state[1]) coverage_reg[1] <= _32_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[2] <= 1'h0;
    else if (state[1]) coverage_reg[2] <= _32_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[3] <= 1'h0;
    else if (state[1]) coverage_reg[3] <= num_detected[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[4] <= 1'h0;
    else if (state[1]) coverage_reg[4] <= num_detected[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[5] <= 1'h0;
    else if (state[1]) coverage_reg[5] <= num_detected[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) coverage_reg[6] <= 1'h0;
    else if (state[1]) coverage_reg[6] <= num_detected[3];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[0] <= 1'h0;
    else if (!_05_) cycle_cnt[0] <= _00_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[1] <= 1'h0;
    else if (!_05_) cycle_cnt[1] <= _00_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[2] <= 1'h0;
    else if (!_05_) cycle_cnt[2] <= _00_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[3] <= 1'h0;
    else if (!_05_) cycle_cnt[3] <= _00_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "controller.sv:111.5-143.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) cycle_cnt[4] <= 1'h0;
    else if (!_05_) cycle_cnt[4] <= _00_[4];
  always @(posedge clk, negedge rstn)
    if (!rstn) state[0] <= 1'h1;
    else state[0] <= _01_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[1] <= 1'h0;
    else state[1] <= _02_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[2] <= 1'h0;
    else state[2] <= _03_;
  always @(posedge clk, negedge rstn)
    if (!rstn) state[3] <= 1'h0;
    else state[3] <= _04_;
  assign { _32_[31:8], _32_[6:3] } = { 24'h000000, num_detected };
  assign coverage = coverage_reg;
  assign pass = pass_reg;
  assign capture_en = state[1];
  assign scan_en = done;
  assign start = state[2];
endmodule

(* src = "cut.sv:1.1-7.10" *)
module cut(in, out);
  (* src = "cut.sv:2.21-2.23" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "cut.sv:3.17-3.20" *)
  output out;
  wire out;
  wire _0_;
  wire _1_;
  assign _0_ = ~(in[0] & in[1]);
  assign _1_ = ~(in[2] & in[3]);
  assign out = ~(_0_ & _1_);
endmodule

(* src = "d_ff.sv:4.1-18.10" *)
module d_ff(clk, rstn, din, q);
  (* src = "d_ff.sv:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "d_ff.sv:6.16-6.20" *)
  input rstn;
  wire rstn;
  (* src = "d_ff.sv:7.16-7.19" *)
  input din;
  wire din;
  (* src = "d_ff.sv:8.16-8.17" *)
  output q;
  reg q;
  (* \always_ff  = 32'd1 *)
  (* src = "d_ff.sv:11.3-16.6" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) q <= 1'h0;
    else q <= din;
endmodule

(* dynports =  1  *)
(* src = "pattern_gen.sv:1.1-21.10" *)
module pattern_lfsr(clk, rstn, start, out);
  (* src = "pattern_gen.sv:4.34-4.37" *)
  input clk;
  wire clk;
  (* src = "pattern_gen.sv:5.34-5.38" *)
  input rstn;
  wire rstn;
  (* src = "pattern_gen.sv:6.17-6.22" *)
  input start;
  wire start;
  (* src = "pattern_gen.sv:7.34-7.37" *)
  output [3:0] out;
  reg [3:0] out;
  (* src = "pattern_gen.sv:10.11-10.19" *)
  wire feedback;
  assign feedback = out[3] ^ out[2];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[0] <= 1'h1;
    else if (start) out[0] <= out[1];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[1] <= 1'h0;
    else if (start) out[1] <= out[2];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[2] <= 1'h0;
    else if (start) out[2] <= out[3];
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_gen.sv:14.5-19.8" *)
  always @(posedge clk, negedge rstn)
    if (!rstn) out[3] <= 1'h0;
    else if (start) out[3] <= feedback;
endmodule

(* dynports =  1  *)
(* src = "scan_reg.sv:6.1-46.10" *)
module scan_chain(clk, rstn, shift_en, capture_en, TDI, TDO, din, q);
  (* src = "scan_reg.sv:9.31-9.34" *)
  input clk;
  wire clk;
  (* src = "scan_reg.sv:10.31-10.35" *)
  input rstn;
  wire rstn;
  (* src = "scan_reg.sv:11.31-11.39" *)
  input shift_en;
  wire shift_en;
  (* src = "scan_reg.sv:12.31-12.41" *)
  input capture_en;
  wire capture_en;
  (* src = "scan_reg.sv:13.31-13.34" *)
  input TDI;
  wire TDI;
  (* src = "scan_reg.sv:14.31-14.34" *)
  output TDO;
  wire TDO;
  (* src = "scan_reg.sv:15.31-15.34" *)
  input [3:0] din;
  wire [3:0] din;
  (* src = "scan_reg.sv:16.31-16.32" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "scan_reg.sv:19.22-19.31" *)
  wire [4:0] scan_wire;
  (* module_not_derived = 32'd1 *)
  (* src = "scan_reg.sv:32.15-41.8" *)
  scan_ff \gen_sff[0].sff  (
    .TDI(TDI),
    .TDO(scan_wire[1]),
    .capture_en(capture_en),
    .clk(clk),
    .din(din[0]),
    .q(q[0]),
    .rstn(rstn),
    .shift_en(shift_en)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "scan_reg.sv:32.15-41.8" *)
  scan_ff \gen_sff[1].sff  (
    .TDI(scan_wire[1]),
    .TDO(scan_wire[2]),
    .capture_en(capture_en),
    .clk(clk),
    .din(din[1]),
    .q(q[1]),
    .rstn(rstn),
    .shift_en(shift_en)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "scan_reg.sv:32.15-41.8" *)
  scan_ff \gen_sff[2].sff  (
    .TDI(scan_wire[2]),
    .TDO(scan_wire[3]),
    .capture_en(capture_en),
    .clk(clk),
    .din(din[2]),
    .q(q[2]),
    .rstn(rstn),
    .shift_en(shift_en)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "scan_reg.sv:32.15-41.8" *)
  scan_ff \gen_sff[3].sff  (
    .TDI(scan_wire[3]),
    .TDO(TDO),
    .capture_en(capture_en),
    .clk(clk),
    .din(din[3]),
    .q(q[3]),
    .rstn(rstn),
    .shift_en(shift_en)
  );
  assign { scan_wire[4], scan_wire[0] } = { TDO, TDI };
endmodule

(* src = "scan_ff.sv:6.1-45.10" *)
module scan_ff(clk, rstn, din, shift_en, capture_en, TDI, TDO, q);
  (* src = "scan_ff.sv:7.16-7.19" *)
  input clk;
  wire clk;
  (* src = "scan_ff.sv:8.16-8.20" *)
  input rstn;
  wire rstn;
  (* src = "scan_ff.sv:10.16-10.19" *)
  input din;
  wire din;
  (* src = "scan_ff.sv:12.16-12.24" *)
  input shift_en;
  wire shift_en;
  (* src = "scan_ff.sv:13.16-13.26" *)
  input capture_en;
  wire capture_en;
  (* src = "scan_ff.sv:15.16-15.19" *)
  input TDI;
  wire TDI;
  (* src = "scan_ff.sv:16.16-16.19" *)
  output TDO;
  wire TDO;
  (* src = "scan_ff.sv:18.16-18.17" *)
  output q;
  wire q;
  wire _0_;
  (* src = "scan_ff.sv:21.9-21.13" *)
  wire d_in;
  assign _0_ = capture_en ? din : q;
  assign d_in = shift_en ? TDI : _0_;
  (* module_not_derived = 32'd1 *)
  (* src = "scan_ff.sv:38.8-43.4" *)
  d_ff df (
    .clk(clk),
    .din(d_in),
    .q(q),
    .rstn(rstn)
  );
  assign TDO = q;
endmodule

(* src = "stuck_models.sv:3.1-64.10" *)
module stuck_at_models(in, smodel, GoodF, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar);
  (* src = "stuck_models.sv:6.21-6.23" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "stuck_models.sv:7.22-7.28" *)
  input [3:0] smodel;
  wire [3:0] smodel;
  (* src = "stuck_models.sv:8.16-8.21" *)
  output GoodF;
  wire GoodF;
  (* src = "stuck_models.sv:9.16-9.22" *)
  output F_at_A;
  wire F_at_A;
  (* src = "stuck_models.sv:9.23-9.32" *)
  output F_at_Abar;
  wire F_at_Abar;
  (* src = "stuck_models.sv:10.16-10.22" *)
  output F_at_B;
  wire F_at_B;
  (* src = "stuck_models.sv:10.23-10.32" *)
  output F_at_Bbar;
  wire F_at_Bbar;
  (* src = "stuck_models.sv:11.16-11.22" *)
  output F_at_C;
  wire F_at_C;
  (* src = "stuck_models.sv:11.23-11.32" *)
  output F_at_Cbar;
  wire F_at_Cbar;
  (* src = "stuck_models.sv:12.16-12.22" *)
  output F_at_D;
  wire F_at_D;
  (* src = "stuck_models.sv:12.23-12.32" *)
  output F_at_Dbar;
  wire F_at_Dbar;
  (* src = "stuck_models.sv:13.16-13.22" *)
  output F_at_X;
  wire F_at_X;
  (* src = "stuck_models.sv:13.23-13.32" *)
  output F_at_Xbar;
  wire F_at_Xbar;
  (* src = "stuck_models.sv:14.16-14.22" *)
  output F_at_Y;
  wire F_at_Y;
  (* src = "stuck_models.sv:14.23-14.32" *)
  output F_at_Ybar;
  wire F_at_Ybar;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  assign _00_ = in[0] & in[1];
  assign _01_ = in[2] & in[3];
  assign _02_ = ~(_00_ | _01_);
  assign GoodF = ~_02_;
  assign _03_ = smodel[0] & smodel[1];
  assign _04_ = smodel[2] & ~(smodel[3]);
  assign _05_ = ~(_03_ & _04_);
  assign _06_ = _01_ & _05_;
  assign F_at_Dbar = _00_ | _06_;
  assign _07_ = smodel[0] & ~(smodel[1]);
  assign _08_ = smodel[3] & ~(smodel[2]);
  assign _09_ = ~(_07_ & _08_);
  assign _10_ = _00_ & _09_;
  assign F_at_Xbar = _01_ | _10_;
  assign _11_ = in[2] | _00_;
  assign _12_ = smodel[1] & ~(smodel[0]);
  assign _13_ = _04_ & _12_;
  assign _14_ = ~(_11_ & _13_);
  assign _15_ = in[3] | _00_;
  assign F_at_D = ~(_02_ & _14_);
  assign _16_ = ~(_08_ & _12_);
  assign F_at_Y = ~(_02_ & _16_);
  assign _17_ = ~(_04_ & _07_);
  assign _18_ = _01_ & _17_;
  assign F_at_Cbar = _00_ | _18_;
  assign _19_ = ~(_03_ & _08_);
  assign _20_ = _01_ & _19_;
  assign F_at_Ybar = _00_ | _20_;
  assign _21_ = ~(smodel[0] | smodel[1]);
  assign _22_ = _04_ & _21_;
  assign _23_ = ~(_15_ & _22_);
  assign F_at_C = ~(_02_ & _23_);
  assign _24_ = in[1] | _01_;
  assign _25_ = ~(smodel[2] | smodel[3]);
  assign _26_ = ~(_21_ & _25_);
  assign _27_ = ~(in[0] | _01_);
  assign _28_ = ~(_26_ & _27_);
  assign F_at_A = _24_ & _28_;
  assign _29_ = ~(_03_ & _25_);
  assign _30_ = _00_ & _29_;
  assign F_at_Bbar = _01_ | _30_;
  assign _31_ = ~(_12_ & _25_);
  assign _32_ = _31_ & ~(_24_);
  assign F_at_B = ~(_27_ | _32_);
  assign _33_ = ~(_07_ & _25_);
  assign _34_ = _00_ & _33_;
  assign F_at_Abar = _01_ | _34_;
  assign _35_ = ~(_08_ & _21_);
  assign F_at_X = ~(_02_ & _35_);
endmodule
