/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module \$paramod$5a749a99f52c3c2473bfdf42ed69512a64c0e60e\controller (clk, rstn, start_ext, num_detected, start, scan_en, capture_en, done, pass, coverage);
  input clk;
  wire clk;
  input rstn;
  wire rstn;
  input start_ext;
  wire start_ext;
  input [3:0] num_detected;
  wire [3:0] num_detected;
  output start;
  wire start;
  output scan_en;
  wire scan_en;
  output capture_en;
  wire capture_en;
  output done;
  wire done;
  output pass;
  wire pass;
  output [6:0] coverage;
  wire [6:0] coverage;
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire [31:0] _115_;
  wire [6:0] coverage_reg;
  wire [4:0] cycle_cnt;
  wire pass_reg;
  wire [3:0] state;
  sky130_fd_sc_hd__clkinv_1 _116_ (
    .A(_057_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(_101_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(_099_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(_051_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _120_ (
    .A(_098_),
    .SLEEP(_097_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(_059_),
    .B(_058_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__or4_1 _122_ (
    .A(_056_),
    .B(_060_),
    .C(_062_),
    .D(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _123_ (
    .A(_098_),
    .B(_101_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _124_ (
    .A(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a22o_1 _125_ (
    .A1(_100_),
    .A2(_067_),
    .B1(_069_),
    .B2(_097_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _126_ (
    .A1(_063_),
    .A2(_097_),
    .B1(_064_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor3_1 _127_ (
    .A(_098_),
    .B(_100_),
    .C(_099_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _128_ (
    .A(_100_),
    .SLEEP(_067_),
    .X(_033_)
  );
  sky130_fd_sc_hd__o41ai_1 _129_ (
    .A1(_056_),
    .A2(_060_),
    .A3(_062_),
    .A4(_066_),
    .B1(_068_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _130_ (
    .A(_056_),
    .SLEEP(_099_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand3b_1 _131_ (
    .A_N(_099_),
    .B(_057_),
    .C(_056_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__and4b_1 _132_ (
    .A_N(_099_),
    .B(_057_),
    .C(_056_),
    .D(_058_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _133_ (
    .A(_058_),
    .B(_072_),
    .X(_074_)
  );
  sky130_fd_sc_hd__a21oi_1 _134_ (
    .A1(_064_),
    .A2(_070_),
    .B1(_074_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _135_ (
    .A(_057_),
    .B(_071_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _136_ (
    .A1(_064_),
    .A2(_070_),
    .B1(_075_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xor2_1 _137_ (
    .A(_056_),
    .B(_099_),
    .X(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _138_ (
    .A1(_064_),
    .A2(_070_),
    .B1(_076_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _139_ (
    .A(_099_),
    .B(_096_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _140_ (
    .A(_093_),
    .SLEEP(_092_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(_095_),
    .B(_064_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3_1 _142_ (
    .A(_093_),
    .B(_094_),
    .C(_092_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a21oi_1 _143_ (
    .A1(_079_),
    .A2(_080_),
    .B1(_077_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(_099_),
    .B(_055_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _145_ (
    .A(_079_),
    .B(_081_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(_054_),
    .A1(_094_),
    .S(_099_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(_053_),
    .A1(_093_),
    .S(_099_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(_052_),
    .A1(_092_),
    .S(_099_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand3_1 _149_ (
    .A(_095_),
    .B(_094_),
    .C(_099_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _150_ (
    .A1(_099_),
    .A2(_065_),
    .B1(_082_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _151_ (
    .A(_095_),
    .SLEEP(_094_),
    .X(_083_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _152_ (
    .A(_094_),
    .SLEEP(_095_),
    .X(_084_)
  );
  sky130_fd_sc_hd__a21o_1 _153_ (
    .A1(_093_),
    .A2(_084_),
    .B1(_064_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o22a_1 _154_ (
    .A1(_099_),
    .A2(_050_),
    .B1(_083_),
    .B2(_085_),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2_0 _155_ (
    .A(_093_),
    .B(_092_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a211oi_1 _156_ (
    .A1(_078_),
    .A2(_083_),
    .B1(_084_),
    .C1(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _157_ (
    .A1_N(_064_),
    .A2_N(_049_),
    .B1(_085_),
    .B2(_087_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(_066_),
    .B(_072_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__and3_1 _159_ (
    .A(_059_),
    .B(_060_),
    .C(_073_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_059_),
    .A2(_073_),
    .B1(_060_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a211oi_1 _161_ (
    .A1(_064_),
    .A2(_069_),
    .B1(_089_),
    .C1(_090_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_059_),
    .B(_073_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a211oi_1 _163_ (
    .A1(_064_),
    .A2(_070_),
    .B1(_088_),
    .C1(_091_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_105_),
    .Q(pass_reg),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_112_),
    .Q(coverage_reg[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_111_),
    .Q(coverage_reg[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_110_),
    .Q(coverage_reg[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_109_),
    .Q(coverage_reg[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_108_),
    .Q(coverage_reg[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_107_),
    .Q(coverage_reg[5]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_106_),
    .Q(coverage_reg[6]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_104_),
    .Q(cycle_cnt[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_103_),
    .Q(cycle_cnt[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_102_),
    .Q(cycle_cnt[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_114_),
    .Q(cycle_cnt[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_113_),
    .Q(cycle_cnt[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _177_ (
    .CLK(clk),
    .D(_001_),
    .Q(state[0]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_003_),
    .Q(state[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_004_),
    .Q(state[3]),
    .RESET_B(rstn)
  );
  assign { _115_[31:8], _115_[6:3] } = { 24'h000000, num_detected };
  assign coverage = coverage_reg;
  assign pass = pass_reg;
  assign capture_en = state[1];
  assign scan_en = done;
  assign start = state[2];
  assign _095_ = num_detected[3];
  assign _093_ = num_detected[1];
  assign _094_ = num_detected[2];
  assign _092_ = num_detected[0];
  assign _059_ = cycle_cnt[3];
  assign _058_ = cycle_cnt[2];
  assign _056_ = cycle_cnt[0];
  assign _060_ = cycle_cnt[4];
  assign _057_ = cycle_cnt[1];
  assign _098_ = state[0];
  assign _101_ = state[3];
  assign _097_ = start_ext;
  assign _001_ = _032_;
  assign _100_ = state[2];
  assign _003_ = _034_;
  assign _099_ = state[1];
  assign _004_ = _035_;
  assign done = _061_;
  assign _002_ = _033_;
  assign _102_ = _036_;
  assign _103_ = _037_;
  assign _104_ = _038_;
  assign _096_ = pass_reg;
  assign _105_ = _039_;
  assign _055_ = coverage_reg[6];
  assign _106_ = _040_;
  assign _054_ = coverage_reg[5];
  assign _107_ = _041_;
  assign _053_ = coverage_reg[4];
  assign _108_ = _042_;
  assign _052_ = coverage_reg[3];
  assign _109_ = _043_;
  assign _051_ = coverage_reg[2];
  assign _110_ = _044_;
  assign _050_ = coverage_reg[1];
  assign _111_ = _045_;
  assign _049_ = coverage_reg[0];
  assign _112_ = _046_;
  assign _113_ = _047_;
  assign _114_ = _048_;
endmodule

module \$paramod\MISR\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, en, smodel, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar, GoodF, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar
, Sign_F_at_C, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Sign_Good);
  input clk;
  wire clk;
  input rstn;
  wire rstn;
  input en;
  wire en;
  input [3:0] smodel;
  wire [3:0] smodel;
  input F_at_A;
  wire F_at_A;
  input F_at_Abar;
  wire F_at_Abar;
  input F_at_B;
  wire F_at_B;
  input F_at_Bbar;
  wire F_at_Bbar;
  input F_at_C;
  wire F_at_C;
  input F_at_Cbar;
  wire F_at_Cbar;
  input F_at_D;
  wire F_at_D;
  input F_at_Dbar;
  wire F_at_Dbar;
  input F_at_X;
  wire F_at_X;
  input F_at_Xbar;
  wire F_at_Xbar;
  input F_at_Y;
  wire F_at_Y;
  input F_at_Ybar;
  wire F_at_Ybar;
  input GoodF;
  wire GoodF;
  output [3:0] Sign_F_at_A;
  wire [3:0] Sign_F_at_A;
  output [3:0] Sign_F_at_Abar;
  wire [3:0] Sign_F_at_Abar;
  output [3:0] Sign_F_at_B;
  wire [3:0] Sign_F_at_B;
  output [3:0] Sign_F_at_Bbar;
  wire [3:0] Sign_F_at_Bbar;
  output [3:0] Sign_F_at_C;
  wire [3:0] Sign_F_at_C;
  output [3:0] Sign_F_at_Cbar;
  wire [3:0] Sign_F_at_Cbar;
  output [3:0] Sign_F_at_D;
  wire [3:0] Sign_F_at_D;
  output [3:0] Sign_F_at_Dbar;
  wire [3:0] Sign_F_at_Dbar;
  output [3:0] Sign_F_at_X;
  wire [3:0] Sign_F_at_X;
  output [3:0] Sign_F_at_Xbar;
  wire [3:0] Sign_F_at_Xbar;
  output [3:0] Sign_F_at_Y;
  wire [3:0] Sign_F_at_Y;
  output [3:0] Sign_F_at_Ybar;
  wire [3:0] Sign_F_at_Ybar;
  output [3:0] Sign_Good;
  wire [3:0] Sign_Good;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  sky130_fd_sc_hd__xnor2_1 _248_ (
    .A(_062_),
    .B(_031_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(_059_),
    .B(_143_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_143_),
    .A2(_144_),
    .B1(_145_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _251_ (
    .A(_076_),
    .B(_078_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _252_ (
    .A(_143_),
    .B(_077_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _253_ (
    .A1(_143_),
    .A2(_146_),
    .B1(_147_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _254_ (
    .A0(_076_),
    .A1(_075_),
    .S(_143_),
    .X(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _255_ (
    .A(_078_),
    .B(_035_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(_143_),
    .B(_075_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _257_ (
    .A1(_143_),
    .A2(_148_),
    .B1(_149_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_052_),
    .B(_054_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(_143_),
    .B(_053_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _260_ (
    .A1(_143_),
    .A2(_150_),
    .B1(_151_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _261_ (
    .A0(_052_),
    .A1(_051_),
    .S(_143_),
    .X(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_054_),
    .B(_029_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(_143_),
    .B(_051_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_143_),
    .A2(_152_),
    .B1(_153_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_044_),
    .B(_046_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_143_),
    .B(_045_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(_143_),
    .A2(_154_),
    .B1(_155_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _268_ (
    .A0(_044_),
    .A1(_043_),
    .S(_143_),
    .X(_099_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_046_),
    .B(_027_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(_143_),
    .B(_043_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _271_ (
    .A1(_143_),
    .A2(_156_),
    .B1(_157_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xnor2_1 _272_ (
    .A(_072_),
    .B(_074_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_143_),
    .B(_073_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _274_ (
    .A1(_143_),
    .A2(_158_),
    .B1(_159_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _275_ (
    .A0(_072_),
    .A1(_071_),
    .S(_143_),
    .X(_102_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(_074_),
    .B(_034_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(_143_),
    .B(_071_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(_143_),
    .A2(_160_),
    .B1(_161_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__mux2_1 _279_ (
    .A0(_058_),
    .A1(_057_),
    .S(_143_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _280_ (
    .A0(_050_),
    .A1(_049_),
    .S(_143_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _281_ (
    .A0(_074_),
    .A1(_073_),
    .S(_143_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _282_ (
    .A0(_062_),
    .A1(_061_),
    .S(_143_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _283_ (
    .A0(_082_),
    .A1(_081_),
    .S(_143_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _284_ (
    .A0(_046_),
    .A1(_045_),
    .S(_143_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _285_ (
    .A0(_070_),
    .A1(_069_),
    .S(_143_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_1 _286_ (
    .A0(_066_),
    .A1(_065_),
    .S(_143_),
    .X(_111_)
  );
  sky130_fd_sc_hd__mux2_1 _287_ (
    .A0(_054_),
    .A1(_053_),
    .S(_143_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _288_ (
    .A0(_086_),
    .A1(_085_),
    .S(_143_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _289_ (
    .A0(_042_),
    .A1(_041_),
    .S(_143_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _290_ (
    .A0(_078_),
    .A1(_077_),
    .S(_143_),
    .X(_115_)
  );
  sky130_fd_sc_hd__xnor2_1 _291_ (
    .A(_040_),
    .B(_042_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_143_),
    .B(_041_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _293_ (
    .A1(_143_),
    .A2(_162_),
    .B1(_163_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _294_ (
    .A0(_040_),
    .A1(_039_),
    .S(_143_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _295_ (
    .A(_042_),
    .B(_026_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_143_),
    .B(_039_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_143_),
    .A2(_164_),
    .B1(_165_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _298_ (
    .A(_068_),
    .B(_070_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(_143_),
    .B(_069_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(_143_),
    .A2(_166_),
    .B1(_167_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__mux2_1 _301_ (
    .A0(_068_),
    .A1(_067_),
    .S(_143_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _302_ (
    .A(_070_),
    .B(_033_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_143_),
    .B(_067_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(_143_),
    .A2(_168_),
    .B1(_169_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(_048_),
    .B(_050_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(_143_),
    .B(_049_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _307_ (
    .A1(_143_),
    .A2(_170_),
    .B1(_171_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _308_ (
    .A0(_048_),
    .A1(_047_),
    .S(_143_),
    .X(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _309_ (
    .A(_050_),
    .B(_028_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_143_),
    .B(_047_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(_143_),
    .A2(_172_),
    .B1(_173_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _312_ (
    .A(_088_),
    .B(_090_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_143_),
    .B(_089_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _314_ (
    .A1(_143_),
    .A2(_174_),
    .B1(_175_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _315_ (
    .A0(_088_),
    .A1(_087_),
    .S(_143_),
    .X(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _316_ (
    .A(_090_),
    .B(_038_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_143_),
    .B(_087_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _318_ (
    .A1(_143_),
    .A2(_176_),
    .B1(_177_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _319_ (
    .A(_084_),
    .B(_086_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(_143_),
    .B(_085_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_143_),
    .A2(_178_),
    .B1(_179_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__mux2_1 _322_ (
    .A0(_084_),
    .A1(_083_),
    .S(_143_),
    .X(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(_086_),
    .B(_037_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _324_ (
    .A(_143_),
    .B(_083_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _325_ (
    .A1(_143_),
    .A2(_180_),
    .B1(_181_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _326_ (
    .A(_056_),
    .B(_058_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(_143_),
    .B(_057_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _328_ (
    .A1(_143_),
    .A2(_182_),
    .B1(_183_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _329_ (
    .A0(_056_),
    .A1(_055_),
    .S(_143_),
    .X(_132_)
  );
  sky130_fd_sc_hd__xnor2_1 _330_ (
    .A(_058_),
    .B(_030_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_143_),
    .B(_055_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _332_ (
    .A1(_143_),
    .A2(_184_),
    .B1(_185_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _333_ (
    .A(_064_),
    .B(_066_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_143_),
    .B(_065_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21oi_1 _335_ (
    .A1(_143_),
    .A2(_186_),
    .B1(_187_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__mux2_1 _336_ (
    .A0(_064_),
    .A1(_063_),
    .S(_143_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _337_ (
    .A(_066_),
    .B(_032_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(_143_),
    .B(_063_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _339_ (
    .A1(_143_),
    .A2(_188_),
    .B1(_189_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(_080_),
    .B(_082_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(_143_),
    .B(_081_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _342_ (
    .A1(_143_),
    .A2(_190_),
    .B1(_191_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__mux2_1 _343_ (
    .A0(_080_),
    .A1(_079_),
    .S(_143_),
    .X(_138_)
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(_082_),
    .B(_036_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor2_1 _345_ (
    .A(_143_),
    .B(_079_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _346_ (
    .A1(_143_),
    .A2(_192_),
    .B1(_193_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_060_),
    .B(_062_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor2_1 _348_ (
    .A(_143_),
    .B(_061_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a21oi_1 _349_ (
    .A1(_143_),
    .A2(_194_),
    .B1(_195_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__mux2_1 _350_ (
    .A0(_060_),
    .A1(_059_),
    .S(_143_),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2_1 _351_ (
    .A0(_090_),
    .A1(_089_),
    .S(_143_),
    .X(_142_)
  );
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(clk),
    .D(_208_),
    .Q(Sign_F_at_X[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(clk),
    .D(_207_),
    .Q(Sign_F_at_X[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(clk),
    .D(_206_),
    .Q(Sign_F_at_X[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _355_ (
    .CLK(clk),
    .D(_211_),
    .Q(Sign_F_at_X[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(clk),
    .D(_205_),
    .Q(Sign_F_at_Abar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _357_ (
    .CLK(clk),
    .D(_204_),
    .Q(Sign_F_at_Abar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(clk),
    .D(_203_),
    .Q(Sign_F_at_Abar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _359_ (
    .CLK(clk),
    .D(_214_),
    .Q(Sign_F_at_Abar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(clk),
    .D(_202_),
    .Q(Sign_F_at_Bbar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _361_ (
    .CLK(clk),
    .D(_201_),
    .Q(Sign_F_at_Bbar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(clk),
    .D(_200_),
    .Q(Sign_F_at_Bbar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _363_ (
    .CLK(clk),
    .D(_217_),
    .Q(Sign_F_at_Bbar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk),
    .D(_199_),
    .Q(Sign_F_at_Xbar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(clk),
    .D(_198_),
    .Q(Sign_F_at_Xbar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk),
    .D(_197_),
    .Q(Sign_F_at_Xbar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _367_ (
    .CLK(clk),
    .D(_220_),
    .Q(Sign_F_at_Xbar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk),
    .D(_196_),
    .Q(Sign_F_at_Cbar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk),
    .D(_246_),
    .Q(Sign_F_at_Cbar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk),
    .D(_245_),
    .Q(Sign_F_at_Cbar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _371_ (
    .CLK(clk),
    .D(_212_),
    .Q(Sign_F_at_Cbar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(_244_),
    .Q(Sign_F_at_Y[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk),
    .D(_243_),
    .Q(Sign_F_at_Y[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(_242_),
    .Q(Sign_F_at_Y[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _375_ (
    .CLK(clk),
    .D(_213_),
    .Q(Sign_F_at_Y[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk),
    .D(_241_),
    .Q(Sign_F_at_D[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(clk),
    .D(_240_),
    .Q(Sign_F_at_D[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk),
    .D(_239_),
    .Q(Sign_F_at_D[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _379_ (
    .CLK(clk),
    .D(_216_),
    .Q(Sign_F_at_D[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk),
    .D(_238_),
    .Q(Sign_F_at_C[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(clk),
    .D(_237_),
    .Q(Sign_F_at_C[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(_236_),
    .Q(Sign_F_at_C[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _383_ (
    .CLK(clk),
    .D(_209_),
    .Q(Sign_F_at_C[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_235_),
    .Q(Sign_F_at_Ybar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_234_),
    .Q(Sign_F_at_Ybar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_233_),
    .Q(Sign_F_at_Ybar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _387_ (
    .CLK(clk),
    .D(_218_),
    .Q(Sign_F_at_Ybar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(_232_),
    .Q(Sign_Good[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(_231_),
    .Q(Sign_Good[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(_230_),
    .Q(Sign_Good[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _391_ (
    .CLK(clk),
    .D(_247_),
    .Q(Sign_Good[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(_229_),
    .Q(Sign_F_at_B[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk),
    .D(_228_),
    .Q(Sign_F_at_B[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_227_),
    .Q(Sign_F_at_B[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _395_ (
    .CLK(clk),
    .D(_210_),
    .Q(Sign_F_at_B[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk),
    .D(_226_),
    .Q(Sign_F_at_Dbar[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clk),
    .D(_225_),
    .Q(Sign_F_at_Dbar[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk),
    .D(_224_),
    .Q(Sign_F_at_Dbar[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _399_ (
    .CLK(clk),
    .D(_215_),
    .Q(Sign_F_at_Dbar[3]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _400_ (
    .CLK(clk),
    .D(_223_),
    .Q(Sign_F_at_A[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _401_ (
    .CLK(clk),
    .D(_222_),
    .Q(Sign_F_at_A[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clk),
    .D(_221_),
    .Q(Sign_F_at_A[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_1 _403_ (
    .CLK(clk),
    .D(_219_),
    .Q(Sign_F_at_A[3]),
    .SET_B(rstn)
  );
  assign _088_ = Sign_Good[1];
  assign _090_ = Sign_Good[3];
  assign _038_ = GoodF;
  assign _084_ = Sign_F_at_Ybar[1];
  assign _086_ = Sign_F_at_Ybar[3];
  assign _037_ = F_at_Ybar;
  assign _080_ = Sign_F_at_Y[1];
  assign _082_ = Sign_F_at_Y[3];
  assign _036_ = F_at_Y;
  assign _076_ = Sign_F_at_Xbar[1];
  assign _078_ = Sign_F_at_Xbar[3];
  assign _035_ = F_at_Xbar;
  assign _072_ = Sign_F_at_X[1];
  assign _074_ = Sign_F_at_X[3];
  assign _034_ = F_at_X;
  assign _068_ = Sign_F_at_Dbar[1];
  assign _070_ = Sign_F_at_Dbar[3];
  assign _033_ = F_at_Dbar;
  assign _064_ = Sign_F_at_D[1];
  assign _066_ = Sign_F_at_D[3];
  assign _032_ = F_at_D;
  assign _060_ = Sign_F_at_Cbar[1];
  assign _062_ = Sign_F_at_Cbar[3];
  assign _031_ = F_at_Cbar;
  assign _056_ = Sign_F_at_C[1];
  assign _058_ = Sign_F_at_C[3];
  assign _030_ = F_at_C;
  assign _052_ = Sign_F_at_Bbar[1];
  assign _054_ = Sign_F_at_Bbar[3];
  assign _029_ = F_at_Bbar;
  assign _048_ = Sign_F_at_B[1];
  assign _050_ = Sign_F_at_B[3];
  assign _028_ = F_at_B;
  assign _044_ = Sign_F_at_Abar[1];
  assign _046_ = Sign_F_at_Abar[3];
  assign _027_ = F_at_Abar;
  assign _040_ = Sign_F_at_A[1];
  assign _042_ = Sign_F_at_A[3];
  assign _026_ = F_at_A;
  assign _059_ = Sign_F_at_Cbar[0];
  assign _143_ = en;
  assign _196_ = _091_;
  assign _077_ = Sign_F_at_Xbar[2];
  assign _197_ = _092_;
  assign _075_ = Sign_F_at_Xbar[0];
  assign _198_ = _093_;
  assign _199_ = _094_;
  assign _053_ = Sign_F_at_Bbar[2];
  assign _200_ = _095_;
  assign _051_ = Sign_F_at_Bbar[0];
  assign _201_ = _096_;
  assign _202_ = _097_;
  assign _045_ = Sign_F_at_Abar[2];
  assign _203_ = _098_;
  assign _043_ = Sign_F_at_Abar[0];
  assign _204_ = _099_;
  assign _205_ = _100_;
  assign _073_ = Sign_F_at_X[2];
  assign _206_ = _101_;
  assign _071_ = Sign_F_at_X[0];
  assign _207_ = _102_;
  assign _208_ = _103_;
  assign _057_ = Sign_F_at_C[2];
  assign _209_ = _104_;
  assign _049_ = Sign_F_at_B[2];
  assign _210_ = _105_;
  assign _211_ = _106_;
  assign _061_ = Sign_F_at_Cbar[2];
  assign _212_ = _107_;
  assign _081_ = Sign_F_at_Y[2];
  assign _213_ = _108_;
  assign _214_ = _109_;
  assign _069_ = Sign_F_at_Dbar[2];
  assign _215_ = _110_;
  assign _065_ = Sign_F_at_D[2];
  assign _216_ = _111_;
  assign _217_ = _112_;
  assign _085_ = Sign_F_at_Ybar[2];
  assign _218_ = _113_;
  assign _041_ = Sign_F_at_A[2];
  assign _219_ = _114_;
  assign _220_ = _115_;
  assign _221_ = _116_;
  assign _039_ = Sign_F_at_A[0];
  assign _222_ = _117_;
  assign _223_ = _118_;
  assign _224_ = _119_;
  assign _067_ = Sign_F_at_Dbar[0];
  assign _225_ = _120_;
  assign _226_ = _121_;
  assign _227_ = _122_;
  assign _047_ = Sign_F_at_B[0];
  assign _228_ = _123_;
  assign _229_ = _124_;
  assign _089_ = Sign_Good[2];
  assign _230_ = _125_;
  assign _087_ = Sign_Good[0];
  assign _231_ = _126_;
  assign _232_ = _127_;
  assign _233_ = _128_;
  assign _083_ = Sign_F_at_Ybar[0];
  assign _234_ = _129_;
  assign _235_ = _130_;
  assign _236_ = _131_;
  assign _055_ = Sign_F_at_C[0];
  assign _237_ = _132_;
  assign _238_ = _133_;
  assign _239_ = _134_;
  assign _063_ = Sign_F_at_D[0];
  assign _240_ = _135_;
  assign _241_ = _136_;
  assign _242_ = _137_;
  assign _079_ = Sign_F_at_Y[0];
  assign _243_ = _138_;
  assign _244_ = _139_;
  assign _245_ = _140_;
  assign _246_ = _141_;
  assign _247_ = _142_;
endmodule

module \$paramod\comparator\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, Sign_Good, Sign_F_at_A, Sign_F_at_Abar, Sign_F_at_B, Sign_F_at_Bbar, Sign_F_at_C, Sign_F_at_Cbar, Sign_F_at_D, Sign_F_at_Dbar, Sign_F_at_X, Sign_F_at_Xbar, Sign_F_at_Y, Sign_F_at_Ybar, Det_A, Det_Abar, Det_B, Det_Bbar, Det_C, Det_Cbar
, Det_D, Det_Dbar, Det_X, Det_Xbar, Det_Y, Det_Ybar, num_detected);
  input clk;
  wire clk;
  input rstn;
  wire rstn;
  input [3:0] Sign_Good;
  wire [3:0] Sign_Good;
  input [3:0] Sign_F_at_A;
  wire [3:0] Sign_F_at_A;
  input [3:0] Sign_F_at_Abar;
  wire [3:0] Sign_F_at_Abar;
  input [3:0] Sign_F_at_B;
  wire [3:0] Sign_F_at_B;
  input [3:0] Sign_F_at_Bbar;
  wire [3:0] Sign_F_at_Bbar;
  input [3:0] Sign_F_at_C;
  wire [3:0] Sign_F_at_C;
  input [3:0] Sign_F_at_Cbar;
  wire [3:0] Sign_F_at_Cbar;
  input [3:0] Sign_F_at_D;
  wire [3:0] Sign_F_at_D;
  input [3:0] Sign_F_at_Dbar;
  wire [3:0] Sign_F_at_Dbar;
  input [3:0] Sign_F_at_X;
  wire [3:0] Sign_F_at_X;
  input [3:0] Sign_F_at_Xbar;
  wire [3:0] Sign_F_at_Xbar;
  input [3:0] Sign_F_at_Y;
  wire [3:0] Sign_F_at_Y;
  input [3:0] Sign_F_at_Ybar;
  wire [3:0] Sign_F_at_Ybar;
  output Det_A;
  wire Det_A;
  output Det_Abar;
  wire Det_Abar;
  output Det_B;
  wire Det_B;
  output Det_Bbar;
  wire Det_Bbar;
  output Det_C;
  wire Det_C;
  output Det_Cbar;
  wire Det_Cbar;
  output Det_D;
  wire Det_D;
  output Det_Dbar;
  wire Det_Dbar;
  output Det_X;
  wire Det_X;
  output Det_Xbar;
  wire Det_Xbar;
  output Det_Y;
  wire Det_Y;
  output Det_Ybar;
  wire Det_Ybar;
  output [3:0] num_detected;
  wire [3:0] num_detected;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  sky130_fd_sc_hd__xnor2_1 _258_ (
    .A(_173_),
    .B(_149_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_172_),
    .B(_148_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(_174_),
    .B(_150_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__xnor2_1 _261_ (
    .A(_175_),
    .B(_151_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand4_1 _262_ (
    .A(_228_),
    .B(_229_),
    .C(_230_),
    .D(_231_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_173_),
    .B(_157_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xnor2_1 _264_ (
    .A(_172_),
    .B(_156_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_174_),
    .B(_158_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(_175_),
    .B(_159_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand4_1 _267_ (
    .A(_232_),
    .B(_233_),
    .C(_234_),
    .D(_235_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xor2_1 _268_ (
    .A(_173_),
    .B(_165_),
    .X(_236_)
  );
  sky130_fd_sc_hd__xor2_1 _269_ (
    .A(_172_),
    .B(_164_),
    .X(_237_)
  );
  sky130_fd_sc_hd__xor2_1 _270_ (
    .A(_174_),
    .B(_166_),
    .X(_238_)
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(_175_),
    .B(_167_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nor4_1 _272_ (
    .A(_236_),
    .B(_237_),
    .C(_238_),
    .D(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(_240_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _274_ (
    .A(_173_),
    .B(_125_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__xnor2_1 _275_ (
    .A(_172_),
    .B(_124_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(_174_),
    .B(_126_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(_175_),
    .B(_127_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__and4_1 _278_ (
    .A(_241_),
    .B(_242_),
    .C(_243_),
    .D(_244_),
    .X(_245_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(_245_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xor2_1 _280_ (
    .A(_173_),
    .B(_129_),
    .X(_246_)
  );
  sky130_fd_sc_hd__xor2_1 _281_ (
    .A(_172_),
    .B(_128_),
    .X(_247_)
  );
  sky130_fd_sc_hd__xor2_1 _282_ (
    .A(_174_),
    .B(_130_),
    .X(_248_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(_175_),
    .B(_131_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor4_1 _284_ (
    .A(_246_),
    .B(_247_),
    .C(_248_),
    .D(_249_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(_250_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _286_ (
    .A(_173_),
    .B(_137_),
    .X(_251_)
  );
  sky130_fd_sc_hd__xor2_1 _287_ (
    .A(_172_),
    .B(_136_),
    .X(_252_)
  );
  sky130_fd_sc_hd__xor2_1 _288_ (
    .A(_174_),
    .B(_138_),
    .X(_253_)
  );
  sky130_fd_sc_hd__xor2_1 _289_ (
    .A(_175_),
    .B(_139_),
    .X(_176_)
  );
  sky130_fd_sc_hd__nor4_1 _290_ (
    .A(_251_),
    .B(_252_),
    .C(_253_),
    .D(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__clkinv_1 _291_ (
    .A(_177_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xnor2_1 _292_ (
    .A(_173_),
    .B(_161_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__xnor2_1 _293_ (
    .A(_172_),
    .B(_160_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _294_ (
    .A(_174_),
    .B(_162_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _295_ (
    .A(_175_),
    .B(_163_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand4_1 _296_ (
    .A(_178_),
    .B(_179_),
    .C(_180_),
    .D(_181_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xor2_1 _297_ (
    .A(_173_),
    .B(_145_),
    .X(_182_)
  );
  sky130_fd_sc_hd__xor2_1 _298_ (
    .A(_172_),
    .B(_144_),
    .X(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _299_ (
    .A(_174_),
    .B(_146_),
    .X(_184_)
  );
  sky130_fd_sc_hd__xor2_1 _300_ (
    .A(_175_),
    .B(_147_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor4_1 _301_ (
    .A(_182_),
    .B(_183_),
    .C(_184_),
    .D(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(_186_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xor2_1 _303_ (
    .A(_173_),
    .B(_153_),
    .X(_187_)
  );
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(_172_),
    .B(_152_),
    .X(_188_)
  );
  sky130_fd_sc_hd__xor2_1 _305_ (
    .A(_174_),
    .B(_154_),
    .X(_189_)
  );
  sky130_fd_sc_hd__xor2_1 _306_ (
    .A(_175_),
    .B(_155_),
    .X(_190_)
  );
  sky130_fd_sc_hd__nor4_1 _307_ (
    .A(_187_),
    .B(_188_),
    .C(_189_),
    .D(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(_191_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(_173_),
    .B(_141_),
    .X(_192_)
  );
  sky130_fd_sc_hd__xor2_1 _310_ (
    .A(_172_),
    .B(_140_),
    .X(_193_)
  );
  sky130_fd_sc_hd__xor2_1 _311_ (
    .A(_174_),
    .B(_142_),
    .X(_194_)
  );
  sky130_fd_sc_hd__xor2_1 _312_ (
    .A(_175_),
    .B(_143_),
    .X(_195_)
  );
  sky130_fd_sc_hd__nor4_1 _313_ (
    .A(_192_),
    .B(_193_),
    .C(_194_),
    .D(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(_196_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__xor2_1 _315_ (
    .A(_173_),
    .B(_169_),
    .X(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _316_ (
    .A(_172_),
    .B(_168_),
    .X(_198_)
  );
  sky130_fd_sc_hd__xor2_1 _317_ (
    .A(_174_),
    .B(_170_),
    .X(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(_175_),
    .B(_171_),
    .X(_200_)
  );
  sky130_fd_sc_hd__nor4_1 _319_ (
    .A(_197_),
    .B(_198_),
    .C(_199_),
    .D(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__clkinv_1 _320_ (
    .A(_201_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _321_ (
    .A(_173_),
    .B(_133_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__xnor2_1 _322_ (
    .A(_172_),
    .B(_132_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(_174_),
    .B(_134_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_175_),
    .B(_135_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand4_1 _325_ (
    .A(_202_),
    .B(_203_),
    .C(_204_),
    .D(_205_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__maj3_1 _326_ (
    .A(_245_),
    .B(_250_),
    .C(_177_),
    .X(_206_)
  );
  sky130_fd_sc_hd__xnor3_1 _327_ (
    .A(_112_),
    .B(_250_),
    .C(_177_),
    .X(_207_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_186_),
    .B(_191_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(_186_),
    .B(_191_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__xnor3_1 _330_ (
    .A(_121_),
    .B(_186_),
    .C(_191_),
    .X(_210_)
  );
  sky130_fd_sc_hd__maj3_1 _331_ (
    .A(_240_),
    .B(_207_),
    .C(_210_),
    .X(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _332_ (
    .A(_206_),
    .B(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__xnor3_1 _333_ (
    .A(_240_),
    .B(_207_),
    .C(_210_),
    .X(_213_)
  );
  sky130_fd_sc_hd__maj3_1 _334_ (
    .A(_118_),
    .B(_120_),
    .C(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__a21oi_1 _335_ (
    .A1(_121_),
    .A2(_209_),
    .B1(_208_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__xnor3_1 _336_ (
    .A(_206_),
    .B(_211_),
    .C(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_214_),
    .B(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__xnor3_1 _338_ (
    .A(_118_),
    .B(_120_),
    .C(_213_),
    .X(_218_)
  );
  sky130_fd_sc_hd__maj3_1 _339_ (
    .A(_196_),
    .B(_201_),
    .C(_218_),
    .X(_219_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(_214_),
    .B(_216_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xnor3_1 _341_ (
    .A(_116_),
    .B(_123_),
    .C(_218_),
    .X(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(_114_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__xor2_1 _343_ (
    .A(_219_),
    .B(_220_),
    .X(_223_)
  );
  sky130_fd_sc_hd__maj3_1 _344_ (
    .A(_219_),
    .B(_220_),
    .C(_222_),
    .X(_224_)
  );
  sky130_fd_sc_hd__maj3_1 _345_ (
    .A(_206_),
    .B(_211_),
    .C(_215_),
    .X(_225_)
  );
  sky130_fd_sc_hd__and2_0 _346_ (
    .A(_217_),
    .B(_225_),
    .X(_226_)
  );
  sky130_fd_sc_hd__a31oi_1 _347_ (
    .A1(_212_),
    .A2(_214_),
    .A3(_216_),
    .B1(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o32ai_1 _348_ (
    .A1(_206_),
    .A2(_211_),
    .A3(_217_),
    .B1(_224_),
    .B2(_226_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__xnor2_1 _349_ (
    .A(_224_),
    .B(_227_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__xor2_1 _350_ (
    .A(_114_),
    .B(_221_),
    .X(_254_)
  );
  sky130_fd_sc_hd__xnor2_1 _351_ (
    .A(_222_),
    .B(_223_),
    .Y(_255_)
  );
  assign _172_ = Sign_Good[0];
  assign _148_ = Sign_F_at_D[0];
  assign _173_ = Sign_Good[1];
  assign _149_ = Sign_F_at_D[1];
  assign _175_ = Sign_Good[3];
  assign _151_ = Sign_F_at_D[3];
  assign _174_ = Sign_Good[2];
  assign _150_ = Sign_F_at_D[2];
  assign Det_D = _118_;
  assign _156_ = Sign_F_at_X[0];
  assign _157_ = Sign_F_at_X[1];
  assign _159_ = Sign_F_at_X[3];
  assign _158_ = Sign_F_at_X[2];
  assign Det_X = _120_;
  assign _164_ = Sign_F_at_Y[0];
  assign _165_ = Sign_F_at_Y[1];
  assign _167_ = Sign_F_at_Y[3];
  assign _166_ = Sign_F_at_Y[2];
  assign Det_Y = _122_;
  assign _124_ = Sign_F_at_A[0];
  assign _125_ = Sign_F_at_A[1];
  assign _127_ = Sign_F_at_A[3];
  assign _126_ = Sign_F_at_A[2];
  assign Det_A = _112_;
  assign _128_ = Sign_F_at_Abar[0];
  assign _129_ = Sign_F_at_Abar[1];
  assign _131_ = Sign_F_at_Abar[3];
  assign _130_ = Sign_F_at_Abar[2];
  assign Det_Abar = _113_;
  assign _136_ = Sign_F_at_Bbar[0];
  assign _137_ = Sign_F_at_Bbar[1];
  assign _139_ = Sign_F_at_Bbar[3];
  assign _138_ = Sign_F_at_Bbar[2];
  assign Det_Bbar = _115_;
  assign _160_ = Sign_F_at_Xbar[0];
  assign _161_ = Sign_F_at_Xbar[1];
  assign _163_ = Sign_F_at_Xbar[3];
  assign _162_ = Sign_F_at_Xbar[2];
  assign Det_Xbar = _121_;
  assign _144_ = Sign_F_at_Cbar[0];
  assign _145_ = Sign_F_at_Cbar[1];
  assign _147_ = Sign_F_at_Cbar[3];
  assign _146_ = Sign_F_at_Cbar[2];
  assign Det_Cbar = _117_;
  assign _152_ = Sign_F_at_Dbar[0];
  assign _153_ = Sign_F_at_Dbar[1];
  assign _155_ = Sign_F_at_Dbar[3];
  assign _154_ = Sign_F_at_Dbar[2];
  assign Det_Dbar = _119_;
  assign _140_ = Sign_F_at_C[0];
  assign _141_ = Sign_F_at_C[1];
  assign _143_ = Sign_F_at_C[3];
  assign _142_ = Sign_F_at_C[2];
  assign Det_C = _116_;
  assign _168_ = Sign_F_at_Ybar[0];
  assign _169_ = Sign_F_at_Ybar[1];
  assign _171_ = Sign_F_at_Ybar[3];
  assign _170_ = Sign_F_at_Ybar[2];
  assign Det_Ybar = _123_;
  assign _132_ = Sign_F_at_B[0];
  assign _133_ = Sign_F_at_B[1];
  assign _135_ = Sign_F_at_B[3];
  assign _134_ = Sign_F_at_B[2];
  assign Det_B = _114_;
  assign num_detected[3] = _257_;
  assign num_detected[2] = _256_;
  assign num_detected[0] = _254_;
  assign num_detected[1] = _255_;
endmodule

module \$paramod\pattern_lfsr\REG_WIDTH=s32'00000000000000000000000000000100 (clk, rstn, start, out);
  input clk;
  wire clk;
  input rstn;
  wire rstn;
  input start;
  wire start;
  output [3:0] out;
  wire [3:0] out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire feedback;
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(_06_),
    .A1(_07_),
    .S(_09_),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(_05_),
    .A1(_06_),
    .S(_09_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(_05_),
    .B(_09_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_08_),
    .B(_04_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(_07_),
    .A1(_08_),
    .S(_09_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfstp_1 _19_ (
    .CLK(clk),
    .D(_11_),
    .Q(out[0]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(clk),
    .D(_10_),
    .Q(out[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(clk),
    .D(_13_),
    .Q(out[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(_12_),
    .Q(out[3]),
    .RESET_B(rstn)
  );
  assign _08_ = out[3];
  assign _05_ = out[0];
  assign _06_ = out[1];
  assign _07_ = out[2];
  assign _09_ = start;
  assign _10_ = _00_;
  assign _11_ = _01_;
  assign _12_ = _02_;
  assign _13_ = _03_;
endmodule

module \$paramod\stuck_at_models\REG_WIDTH=s32'00000000000000000000000000000100 (in, smodel, GoodF, F_at_A, F_at_Abar, F_at_B, F_at_Bbar, F_at_C, F_at_Cbar, F_at_D, F_at_Dbar, F_at_X, F_at_Xbar, F_at_Y, F_at_Ybar);
  input [3:0] in;
  wire [3:0] in;
  input [3:0] smodel;
  wire [3:0] smodel;
  output GoodF;
  wire GoodF;
  output F_at_A;
  wire F_at_A;
  output F_at_Abar;
  wire F_at_Abar;
  output F_at_B;
  wire F_at_B;
  output F_at_Bbar;
  wire F_at_Bbar;
  output F_at_C;
  wire F_at_C;
  output F_at_Cbar;
  wire F_at_Cbar;
  output F_at_D;
  wire F_at_D;
  output F_at_Dbar;
  wire F_at_Dbar;
  output F_at_X;
  wire F_at_X;
  output F_at_Xbar;
  wire F_at_Xbar;
  output F_at_Y;
  wire F_at_Y;
  output F_at_Ybar;
  wire F_at_Ybar;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  sky130_fd_sc_hd__nand2_1 _67_ (
    .A(_49_),
    .B(_50_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nand2_1 _68_ (
    .A(_51_),
    .B(_52_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__a22oi_1 _69_ (
    .A1(_49_),
    .A2(_50_),
    .B1(_51_),
    .B2(_52_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__clkinv_1 _70_ (
    .A(_55_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__and2_0 _71_ (
    .A(_63_),
    .B(_64_),
    .X(_56_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _72_ (
    .A(_65_),
    .SLEEP(_66_),
    .X(_57_)
  );
  sky130_fd_sc_hd__a31oi_1 _73_ (
    .A1(_53_),
    .A2(_56_),
    .A3(_57_),
    .B1(_55_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _74_ (
    .A(_66_),
    .SLEEP(_65_),
    .X(_58_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _75_ (
    .A(_63_),
    .SLEEP(_64_),
    .X(_59_)
  );
  sky130_fd_sc_hd__a31oi_1 _76_ (
    .A1(_54_),
    .A2(_58_),
    .A3(_59_),
    .B1(_55_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _77_ (
    .A(_64_),
    .SLEEP(_63_),
    .X(_60_)
  );
  sky130_fd_sc_hd__a31o_1 _78_ (
    .A1(_51_),
    .A2(_57_),
    .A3(_60_),
    .B1(_48_),
    .X(_42_)
  );
  sky130_fd_sc_hd__a21o_1 _79_ (
    .A1(_58_),
    .A2(_60_),
    .B1(_48_),
    .X(_46_)
  );
  sky130_fd_sc_hd__a31oi_1 _80_ (
    .A1(_53_),
    .A2(_57_),
    .A3(_59_),
    .B1(_55_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__a31oi_1 _81_ (
    .A1(_53_),
    .A2(_56_),
    .A3(_58_),
    .B1(_55_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nor2_1 _82_ (
    .A(_63_),
    .B(_64_),
    .Y(_61_)
  );
  sky130_fd_sc_hd__a31o_1 _83_ (
    .A1(_52_),
    .A2(_57_),
    .A3(_61_),
    .B1(_48_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nor2_1 _84_ (
    .A(_65_),
    .B(_66_),
    .Y(_62_)
  );
  sky130_fd_sc_hd__a31o_1 _85_ (
    .A1(_50_),
    .A2(_61_),
    .A3(_62_),
    .B1(_48_),
    .X(_36_)
  );
  sky130_fd_sc_hd__a31oi_1 _86_ (
    .A1(_54_),
    .A2(_56_),
    .A3(_62_),
    .B1(_55_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__a31o_1 _87_ (
    .A1(_49_),
    .A2(_60_),
    .A3(_62_),
    .B1(_48_),
    .X(_38_)
  );
  sky130_fd_sc_hd__a31oi_1 _88_ (
    .A1(_54_),
    .A2(_59_),
    .A3(_62_),
    .B1(_55_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a21o_1 _89_ (
    .A1(_58_),
    .A2(_61_),
    .B1(_48_),
    .X(_44_)
  );
  assign _49_ = in[0];
  assign _50_ = in[1];
  assign _51_ = in[2];
  assign _52_ = in[3];
  assign GoodF = _48_;
  assign _63_ = smodel[0];
  assign _64_ = smodel[1];
  assign _65_ = smodel[2];
  assign _66_ = smodel[3];
  assign F_at_Dbar = _43_;
  assign F_at_Xbar = _45_;
  assign F_at_D = _42_;
  assign F_at_Y = _46_;
  assign F_at_Cbar = _41_;
  assign F_at_Ybar = _47_;
  assign F_at_C = _40_;
  assign F_at_A = _36_;
  assign F_at_Bbar = _39_;
  assign F_at_B = _38_;
  assign F_at_Abar = _37_;
  assign F_at_X = _44_;
endmodule

module bist_top(rstn, clk, start_ext, smodel, out_pattern, cut_out, done, pass, coverage, num_detected);
  input rstn;
  wire rstn;
  input clk;
  wire clk;
  input start_ext;
  wire start_ext;
  input [3:0] smodel;
  wire [3:0] smodel;
  output [3:0] out_pattern;
  wire [3:0] out_pattern;
  output cut_out;
  wire cut_out;
  output done;
  wire done;
  output pass;
  wire pass;
  output [6:0] coverage;
  wire [6:0] coverage;
  output [3:0] num_detected;
  wire [3:0] num_detected;
  wire Det_A;
  wire Det_Abar;
  wire Det_B;
  wire Det_Bbar;
  wire Det_C;
  wire Det_Cbar;
  wire Det_D;
  wire Det_Dbar;
  wire Det_X;
  wire Det_Xbar;
  wire Det_Y;
  wire Det_Ybar;
  wire F_at_A;
  wire F_at_Abar;
  wire F_at_B;
  wire F_at_Bbar;
  wire F_at_C;
  wire F_at_Cbar;
  wire F_at_D;
  wire F_at_Dbar;
  wire F_at_X;
  wire F_at_Xbar;
  wire F_at_Y;
  wire F_at_Ybar;
  wire GoodF;
  wire [3:0] Sign_F_at_A;
  wire [3:0] Sign_F_at_Abar;
  wire [3:0] Sign_F_at_B;
  wire [3:0] Sign_F_at_Bbar;
  wire [3:0] Sign_F_at_C;
  wire [3:0] Sign_F_at_Cbar;
  wire [3:0] Sign_F_at_D;
  wire [3:0] Sign_F_at_Dbar;
  wire [3:0] Sign_F_at_X;
  wire [3:0] Sign_F_at_Xbar;
  wire [3:0] Sign_F_at_Y;
  wire [3:0] Sign_F_at_Ybar;
  wire [3:0] Sign_Good;
  wire capture_en;
  wire scan_en;
  wire start;
  cut u_cut (
    .in(out_pattern),
    .out(cut_out)
  );
  \$paramod\comparator\REG_WIDTH=s32'00000000000000000000000000000100  uut_comp (
    .Det_A(Det_A),
    .Det_Abar(Det_Abar),
    .Det_B(Det_B),
    .Det_Bbar(Det_Bbar),
    .Det_C(Det_C),
    .Det_Cbar(Det_Cbar),
    .Det_D(Det_D),
    .Det_Dbar(Det_Dbar),
    .Det_X(Det_X),
    .Det_Xbar(Det_Xbar),
    .Det_Y(Det_Y),
    .Det_Ybar(Det_Ybar),
    .Sign_F_at_A(Sign_F_at_A),
    .Sign_F_at_Abar(Sign_F_at_Abar),
    .Sign_F_at_B(Sign_F_at_B),
    .Sign_F_at_Bbar(Sign_F_at_Bbar),
    .Sign_F_at_C(Sign_F_at_C),
    .Sign_F_at_Cbar(Sign_F_at_Cbar),
    .Sign_F_at_D(Sign_F_at_D),
    .Sign_F_at_Dbar(Sign_F_at_Dbar),
    .Sign_F_at_X(Sign_F_at_X),
    .Sign_F_at_Xbar(Sign_F_at_Xbar),
    .Sign_F_at_Y(Sign_F_at_Y),
    .Sign_F_at_Ybar(Sign_F_at_Ybar),
    .Sign_Good(Sign_Good),
    .clk(clk),
    .num_detected(num_detected),
    .rstn(rstn)
  );
  \$paramod$5a749a99f52c3c2473bfdf42ed69512a64c0e60e\controller  uut_controller (
    .capture_en(capture_en),
    .clk(clk),
    .coverage(coverage),
    .done(done),
    .num_detected(num_detected),
    .pass(pass),
    .rstn(rstn),
    .scan_en(scan_en),
    .start(start),
    .start_ext(start_ext)
  );
  \$paramod\MISR\REG_WIDTH=s32'00000000000000000000000000000100  uut_misr (
    .F_at_A(F_at_A),
    .F_at_Abar(F_at_Abar),
    .F_at_B(F_at_B),
    .F_at_Bbar(F_at_Bbar),
    .F_at_C(F_at_C),
    .F_at_Cbar(F_at_Cbar),
    .F_at_D(F_at_D),
    .F_at_Dbar(F_at_Dbar),
    .F_at_X(F_at_X),
    .F_at_Xbar(F_at_Xbar),
    .F_at_Y(F_at_Y),
    .F_at_Ybar(F_at_Ybar),
    .GoodF(GoodF),
    .Sign_F_at_A(Sign_F_at_A),
    .Sign_F_at_Abar(Sign_F_at_Abar),
    .Sign_F_at_B(Sign_F_at_B),
    .Sign_F_at_Bbar(Sign_F_at_Bbar),
    .Sign_F_at_C(Sign_F_at_C),
    .Sign_F_at_Cbar(Sign_F_at_Cbar),
    .Sign_F_at_D(Sign_F_at_D),
    .Sign_F_at_Dbar(Sign_F_at_Dbar),
    .Sign_F_at_X(Sign_F_at_X),
    .Sign_F_at_Xbar(Sign_F_at_Xbar),
    .Sign_F_at_Y(Sign_F_at_Y),
    .Sign_F_at_Ybar(Sign_F_at_Ybar),
    .Sign_Good(Sign_Good),
    .clk(clk),
    .en(start),
    .rstn(rstn),
    .smodel(smodel)
  );
  \$paramod\stuck_at_models\REG_WIDTH=s32'00000000000000000000000000000100  uut_model (
    .F_at_A(F_at_A),
    .F_at_Abar(F_at_Abar),
    .F_at_B(F_at_B),
    .F_at_Bbar(F_at_Bbar),
    .F_at_C(F_at_C),
    .F_at_Cbar(F_at_Cbar),
    .F_at_D(F_at_D),
    .F_at_Dbar(F_at_Dbar),
    .F_at_X(F_at_X),
    .F_at_Xbar(F_at_Xbar),
    .F_at_Y(F_at_Y),
    .F_at_Ybar(F_at_Ybar),
    .GoodF(GoodF),
    .in(out_pattern),
    .smodel(smodel)
  );
  \$paramod\pattern_lfsr\REG_WIDTH=s32'00000000000000000000000000000100  uut_pattern (
    .clk(clk),
    .out(out_pattern),
    .rstn(rstn),
    .start(start)
  );
endmodule

module cut(clk, in, out);
  input clk;
  wire clk;
  input [3:0] in;
  wire [3:0] in;
  output out;
  wire out;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  sky130_fd_sc_hd__a22o_1 _7_ (
    .A1(_2_),
    .A2(_3_),
    .B1(_4_),
    .B2(_5_),
    .X(_6_)
  );
  assign _2_ = in[0];
  assign _3_ = in[1];
  assign _4_ = in[2];
  assign _5_ = in[3];
  assign out = _6_;
endmodule
