/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module cut(clk, in, out);
  input clk;
  wire clk;
  input [3:0] in;
  wire [3:0] in;
  output out;
  wire out;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  sky130_fd_sc_hd__a22o_1 _7_ (
    .A1(_2_),
    .A2(_3_),
    .B1(_4_),
    .B2(_5_),
    .X(_6_)
  );
  assign _2_ = in[0];
  assign _3_ = in[1];
  assign _4_ = in[2];
  assign _5_ = in[3];
  assign out = _6_;
endmodule
